package aps.ics.assembly.icd

// This file contains the API for APS and was generated by the icd-db command.
// DO NOT EDIT.
// See https://github.com/tmtsoftware/icd for more information.

import csw.params.core.generics.KeyType._
import csw.params.commands.CommandName
import csw.params.events._
import csw.prefix.models._
import csw.params.core.generics._
import csw.params.core.models._
import csw.params.core.models.Coords._
import csw.time.core.models._

/**
 * Top level API for: APS
 */
//noinspection ScalaUnusedSymbol
object AbeEnclosureKeys {
  val subsystem = "APS"

  /** API for Assembly: APS.ICS.ABE.Enclosure */
  object `ICS.ABE.Enclosure` {
    val prefix: Prefix = Prefix(Subsystem.APS, "ICS.ABE.Enclosure")

    /** ABE Enclosure status event */
    object StatusEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("status"))

      /** Current Assembly State */
      val assemblyStateKey: GChoiceKey = ChoiceKey.make("assemblyState", "READY", "DEGRADED", "FAULTED")

      /** Current HCD State of the HCD that the assembly communicates with */
      val hcdStateKey: GChoiceKey = ChoiceKey.make("hcdState", "UNINITIALIZED", "READY", "FAULTED")

      /** Status of last command */
      val commandStateKey: GChoiceKey = ChoiceKey.make("commandState", "IDLE", "PROCESSING", "ERROR_RECOVERY", "FAILED")

      /** Purge Air Flow Rate (liters/sec) */
      val purgeAirFlowRateKey: Key[Float] = FloatKey.make("purgeAirFlowRate", Units.NoUnits)

      /** Overall Coolant Pressure (bars) */
      val coolantPressureKey: Key[Float] = FloatKey.make("coolantPressure", Units.bar)

      /** The state of the sensor detecting coolant leaks at the bench */
      val benchCoolantLeakSensorFaultDetectionKey: GChoiceKey =
        ChoiceKey.make("benchCoolantLeakSensorFaultDetection", "READY", "FAULTED")

      /** The state of the sensor detecting coolant leaks between the electronics enclosure and bench */
      val rackToBenchCoolantLeakSensorFaultDetectionKey: GChoiceKey =
        ChoiceKey.make("rackToBenchCoolantLeakSensorFaultDetection", "READY", "FAULTED")

      /** The state of the sensor detecting coolant leaks in the electronics enclosure */
      val rackCoolantLeakSensorFaultDetectionKey: GChoiceKey =
        ChoiceKey.make("rackCoolantLeakSensorFaultDetection", "READY", "FAULTED")

      /** Coolant leak detection state within the APS Bench */
      val benchCoolantLeakSensorDetectionStateKey: GChoiceKey =
        ChoiceKey.make("benchCoolantLeakSensorDetectionState", "NONE", "LEAK_DETECTED")

      /** Coolant leak detection state between the APS Electronics Rack and the APS Bench */
      val rackToBenchCoolantLeakSensorDetectionStateKey: GChoiceKey =
        ChoiceKey.make("rackToBenchCoolantLeakSensorDetectionState", "NONE", "LEAK_DETECTED")

      /** Coolant leak detection state within the APS Electronics Rack */
      val rackCoolantLeakSensorDetectionStateKey: GChoiceKey =
        ChoiceKey.make("rackCoolantLeakSensorDetectionState", "NONE", "LEAK_DETECTED")

      /** PSH Detector Coolant Flow Rate (liters/sec) */
      val pshCoolantFlowRateKey: Key[Float] = FloatKey.make("pshCoolantFlowRate", Units.NoUnits)

      /** PIT Detector Coolant Flow Rate (liters/sec) */
      val pitCoolantFlowRateKey: Key[Float] = FloatKey.make("pitCoolantFlowRate", Units.NoUnits)

      /** APT Detector Coolant Flow Rate (liters/sec) */
      val aptCoolantFlowRateKey: Key[Float] = FloatKey.make("aptCoolantFlowRate", Units.NoUnits)

      /** LOWFS Detector Coolant Flow Rate (liters/sec) */
      val lowfsCoolantFlowRateKey: Key[Float] = FloatKey.make("lowfsCoolantFlowRate", Units.NoUnits)

      /** Current shutter temperature (deg C) */
      val shutterTemperatureKey: Key[Float] = FloatKey.make("shutterTemperature", Units.degC)

      /** Current shutter relative humidity (%) */
      val shutterHumidityKey: Key[Float] = FloatKey.make("shutterHumidity", Units.percent)

      /** Current shutter dew point (deg C) */
      val shutterDewPointKey: Key[Float] = FloatKey.make("shutterDewPoint", Units.degC)

      /** Current PSH detector temperature (deg C) */
      val pshTemperatureKey: Key[Float] = FloatKey.make("pshTemperature", Units.degC)

      /** Current PSH detector relative humidity (%) */
      val pshHumidityKey: Key[Float] = FloatKey.make("pshHumidity", Units.percent)

      /** Current PSH detector dew point (deg C) */
      val pshDewPointKey: Key[Float] = FloatKey.make("pshDewPoint", Units.degC)

      /** Current Electronics Cabinet temperature (deg C) */
      val electronicsCabinetTemperatureKey: Key[Float] = FloatKey.make("electronicsCabinetTemperature", Units.degC)

      /** Current Electronics Cabinet relative humidity (%) */
      val electronicsCabinetHumidityKey: Key[Float] = FloatKey.make("electronicsCabinetHumidity", Units.percent)

      /** Current Electronics Cabinet dew point (deg C) */
      val electronicsCabinetDewPointKey: Key[Float] = FloatKey.make("electronicsCabinetDewPoint", Units.degC)

      /**
       * Placeholder for temperature readings from temperature sensors placed at various positions on the bench. Number of sensors
       * and positions TBD
       */
      val placeholderCurrentTemperatureKey: Key[Float] = FloatKey.make("placeholderCurrentTemperature", Units.degC)

    }

    /** Event used to communicate a command failure to the user interface and/or Alignment Procedure Sequencer. */
    object ApsCommandFailureEventEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("apsCommandFailureEvent"))

      /** The user readable name of the source assembly or service that published the event */
      val sourceAssemblyKey: Key[String] = StringKey.make("sourceAssembly")

      /** Failure message supplied by the event source. */
      val messageKey: Key[String] = StringKey.make("message")

      /**
       * For failures and errors that have recovery modes (e.g. motion assemblies and detector assemblies) a state for the
       * progress of the recovery is given: started, completed, aborted. For failures that do not support auto recovery, the state
       * is NOT USED.
       */
      val recoveryStateKey: GChoiceKey = ChoiceKey.make("recoveryState", "STARTED", "COMPLETED", "ABORTED", "NOT_USED")

      /** The current auto-recovery retry number. */
      val recoveryRetryIndexKey: Key[Int] = IntKey.make("recoveryRetryIndex", Units.NoUnits)

      /** The total number of auto-recovery retries before recovery is abandoned. */
      val recoveryRetryCountKey: Key[Int] = IntKey.make("recoveryRetryCount", Units.NoUnits)

      /** Indicates if the current retry succeeded or failed. */
      val recoveryRetryStateKey: GChoiceKey = ChoiceKey.make("recoveryRetryState", "FAILURE", "SUCCESS")

    }

    /** assembly startup metrics */
    object StartupMetricsEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("startupMetrics"))

      /** Assembly initialization start time */
      val initStartTimeKey: Key[TAITime] = TAITimeKey.make("initStartTime")

      /** Assembly initialization completed time */
      val initCompletedTimeKey: Key[TAITime] = TAITimeKey.make("initCompletedTime")

    }

    /** Commands the purge air on or off. */
    object CommandPurgeAirCommand {
      val commandName: CommandName = CommandName("commandPurgeAir")

      /** The desired command action: on or off. */
      val actionKey: GChoiceKey = ChoiceKey.make("action", "ON", "OFF")

    }

    /** Controls valve to turn on/off coolant flow */
    object CommandCoolantControlValveCommand {
      val commandName: CommandName = CommandName("commandCoolantControlValve")

      /** The desired command action: on or off. */
      val actionKey: GChoiceKey = ChoiceKey.make("action", "ON", "OFF")

    }

  }

}
