package aps.ics.assembly.icd

// This file contains the API for APS and was generated by the icd-db command.
// DO NOT EDIT.
// See https://github.com/tmtsoftware/icd for more information.

import csw.params.core.generics.KeyType._
import csw.params.commands.CommandName
import csw.params.events._
import csw.prefix.models._
import csw.params.core.generics._
import csw.params.core.models._
import csw.params.core.models.Coords._
import csw.time.core.models._

/**
 * Top level API for: APS
 */
//noinspection ScalaUnusedSymbol
object AbeShutterKeys {
  val subsystem = "APS"

  /** API for Assembly: APS.ICS.ABE.Shutter */
  object `ICS.ABE.Shutter` {
    val prefix: Prefix = Prefix(Subsystem.APS, "ICS.ABE.Shutter")

    /** ABE Shutter status event */
    object StatusEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("status"))

      /** Current Assembly State */
      val assemblyStateKey: GChoiceKey = ChoiceKey.make("assemblyState", "READY", "DEGRADED", "FAULTED")

      /** Current HCD State of the HCD that the assembly communicates with */
      val hcdStateKey: GChoiceKey = ChoiceKey.make("hcdState", "UNINITIALIZED", "READY", "FAULTED")

      /** Status of last command */
      val commandStateKey: GChoiceKey = ChoiceKey.make("commandState", "IDLE", "PROCESSING", "ERROR_RECOVERY", "FAILED")

      /** Shutter Blade A state */
      val shutterBladeAStateKey: GChoiceKey = ChoiceKey.make("shutterBladeAState", "OPEN", "CLOSED")

      /** Shutter Blade B state */
      val shutterBladeBStateKey: GChoiceKey = ChoiceKey.make("shutterBladeBState", "OPEN", "CLOSED")

      /** Shutter Error indicator bit state */
      val shutterErrorIndicatorKey: GChoiceKey = ChoiceKey.make("shutterErrorIndicator", "YES", "NO")

    }

    /** Event used to communicate a command failure to the user interface and/or Alignment Procedure Sequencer. */
    object ApsCommandFailureEventEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("apsCommandFailureEvent"))

      /** The user readable name of the source assembly or service that published the event */
      val sourceAssemblyKey: Key[String] = StringKey.make("sourceAssembly")

      /** Failure message supplied by the event source. */
      val messageKey: Key[String] = StringKey.make("message")

      /**
       * For failures and errors that have recovery modes (e.g. motion assemblies and detector assemblies) a state for the
       * progress of the recovery is given: started, completed, aborted. For failures that do not support auto recovery, the state
       * is NOT USED.
       */
      val recoveryStateKey: GChoiceKey = ChoiceKey.make("recoveryState", "STARTED", "COMPLETED", "ABORTED", "NOT_USED")

      /** The current auto-recovery retry number. */
      val recoveryRetryIndexKey: Key[Int] = IntKey.make("recoveryRetryIndex", Units.NoUnits)

      /** The total number of auto-recovery retries before recovery is abandoned. */
      val recoveryRetryCountKey: Key[Int] = IntKey.make("recoveryRetryCount", Units.NoUnits)

      /** Indicates if the current retry succeeded or failed. */
      val recoveryRetryStateKey: GChoiceKey = ChoiceKey.make("recoveryRetryState", "FAILURE", "SUCCESS")

    }

    /** assembly startup metrics */
    object StartupMetricsEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("startupMetrics"))

      /** Assembly initialization start time */
      val initStartTimeKey: Key[TAITime] = TAITimeKey.make("initStartTime")

      /** Assembly initialization completed time */
      val initCompletedTimeKey: Key[TAITime] = TAITimeKey.make("initCompletedTime")

      /** Assembly configuration start time */
      val configureStartTimeKey: Key[TAITime] = TAITimeKey.make("configureStartTime")

      /** Assembly configuration completed time */
      val configureCompletedTimeKey: Key[TAITime] = TAITimeKey.make("configureCompletedTime")

    }

    /** Commands shutter to open or close. */
    object CommandShutterCommand {
      val commandName: CommandName = CommandName("commandShutter")

      /** The desired command action: open or close */
      val commandKey: GChoiceKey = ChoiceKey.make("command", "OPEN", "CLOSE")

    }

  }

}
