package aps.ics.assembly.icd

// This file contains the API for APS and was generated by the icd-db command.
// DO NOT EDIT.
// See https://github.com/tmtsoftware/icd for more information.

import csw.params.core.generics.KeyType._
import csw.params.commands.CommandName
import csw.params.events._
import csw.prefix.models._
import csw.params.core.generics._
import csw.params.core.models._
import csw.params.core.models.Coords._
import csw.time.core.models._

/**
 * Top level API for: APS
 */
//noinspection ScalaUnusedSymbol
object AptDetectorKeys {
  val subsystem = "APS"

  /** API for Assembly: APS.ICS.APT.Detector */
  object `ICS.APT.Detector` {
    val prefix: Prefix = Prefix(Subsystem.APS, "ICS.APT.Detector")

    /** APT Detector status event. This paramter set is published at 1 Hz */
    object StatusEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("status"))

      /** Current Assembly State */
      val assemblyStateKey: GChoiceKey = ChoiceKey.make("assemblyState", "READY", "DEGRADED", "FAULTED")

      /** Cooling subsystem health classification (mapped from device-specific states) */
      val coolingHealthKey: GChoiceKey = ChoiceKey.make("coolingHealth", "Good", "Degraded", "Bad")

      /** Camera detected and initialized */
      val cameraPresentKey: Key[Boolean] = BooleanKey.make("cameraPresent")

      /** Camera acquisition state */
      val cameraAcquisitionStateKey: GChoiceKey =
        ChoiceKey.make("cameraAcquisitionState", "IDLE", "BUSY", "STREAMING", "PAUSED", "FAULT", "RECOVERING")

    }

    /** APT Detector temperature status event. */
    object TemperatureStatusEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("temperatureStatus"))

      /** The current temperature of the detector */
      val detectorTemperatureKey: Key[Float] = FloatKey.make("detectorTemperature", Units.degC)

      /** Configured temperature set point */
      val temperatureSetPointKey: Key[Float] = FloatKey.make("temperatureSetPoint", Units.degC)

    }

    /**
     * APT Detector setupStatus event. These parameters change only at the start of a procedure and are only published at the
     * start of an alignment procedure
     */
    object SetupStatusEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("setupStatus"))

      /** The buffer size in bytes required to store the data for one frame. */
      val imageSizeKey: Key[Int] = IntKey.make("imageSize", Units.NoUnits)

      /** Current acquisition mode. */
      val acquisitionModeKey: GChoiceKey = ChoiceKey.make("acquisitionMode", "SINGLE", "BURST", "LOOP")

      /** Memory strategy used for data capture. */
      val bufferModelKey: GChoiceKey = ChoiceKey.make("bufferModel", "SINGLE", "CONTAINER", "RING")

      /** Continuous mode frame rate. */
      val frameRateKey: Key[Float] = FloatKey.make("frameRate", Units.hertz)

      /** Shared-memory location of the active buffer. */
      val pathKey: Key[String] = StringKey.make("path", Units.NoUnits)

      /** Horizontal Binning in pixels */
      val hBinKey: Key[Int] = IntKey.make("hBin", Units.pix)

      /** Vertical Binning in pixels */
      val vBinKey: Key[Int] = IntKey.make("vBin", Units.pix)

    }

    /**
     * APT Detector guidingStatus event. These parameters are changed during aquisition in response to guiding pixel flux values
     * change. Published upon change.
     */
    object GuidingStatusEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("guidingStatus"))

      /** Current gain mode. */
      val gainModeKey: GChoiceKey = ChoiceKey.make("gainMode", "12=bit", "16-bit")

      /** Integration time. */
      val integrationTimeKey: Key[Float] = FloatKey.make("integrationTime", Units.second)

      /** Starting row of region of interest */
      val roiStartRowKey: Key[Int] = IntKey.make("roiStartRow", Units.pix)

      /** Starting col of region of interest */
      val roiStartColKey: Key[Int] = IntKey.make("roiStartCol", Units.pix)

      /** Number of rows in the region of interest */
      val roiHeightKey: Key[Int] = IntKey.make("roiHeight", Units.pix)

      /** Number of columns in the region of interest */
      val roiWidthKey: Key[Int] = IntKey.make("roiWidth", Units.pix)

    }

    /**
     * APT Detector configStatus event. These parameters typically do not change value during normal operations, but might change
     * during instrument characterization and AIV. Only published on when the assembly sends the configure command to the Andor
     * HCD
     */
    object ConfigStatusEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("configStatus"))

      /** The format of the data stream. */
      val pixelEncodingKey: GChoiceKey =
        ChoiceKey.make("pixelEncoding", "Mono12", "Mono12Packed", "Mono16", "Mono32", "Mono12CXP", "Mono18")

      /** Pixel readout rate. */
      val pixelReadoutRateKey: GChoiceKey = ChoiceKey.make("pixelReadoutRate", "100MHz", "200MHz")

      /** When true the spurious noise filter is enabled. */
      val spuriousNoiseFilterKey: Key[Boolean] = BooleanKey.make("spuriousNoiseFilter")

    }

    /** Event used to communicate a command failure to the user interface and/or Alignment Procedure Sequencer. */
    object ApsCommandFailureEventEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("apsCommandFailureEvent"))

      /** The user readable name of the source assembly or service that published the event */
      val sourceAssemblyKey: Key[String] = StringKey.make("sourceAssembly")

      /** Failure message supplied by the event source. */
      val messageKey: Key[String] = StringKey.make("message")

      /**
       * For failures and errors that have recovery modes (e.g. motion assemblies and detector assemblies) a state for the
       * progress of the recovery is given: started, completed, aborted. For failures that do not support auto recovery, the state
       * is NOT USED.
       */
      val recoveryStateKey: GChoiceKey = ChoiceKey.make("recoveryState", "STARTED", "COMPLETED", "ABORTED", "NOT_USED")

      /** The current auto-recovery retry number. */
      val recoveryRetryIndexKey: Key[Int] = IntKey.make("recoveryRetryIndex", Units.NoUnits)

      /** The total number of auto-recovery retries before recovery is abandoned. */
      val recoveryRetryCountKey: Key[Int] = IntKey.make("recoveryRetryCount", Units.NoUnits)

      /** Indicates if the current retry succeeded or failed. */
      val recoveryRetryStateKey: GChoiceKey = ChoiceKey.make("recoveryRetryState", "FAILURE", "SUCCESS")

    }

    /**
     * APT Detector exposure store completed event. Used to notify APS-PEAS of incoming images just stored on the APS Shared disk
     */
    object ExposureStoreCompletedEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("exposureStoreCompleted"))

      /** The name of the file on the APS Shared Disk */
      val filenameKey: Key[String] = StringKey.make("filename")

    }

    /**
     * APT Detector exposure archive completed event. Used to update APS-PEAS Exposure Service of images that have been stored to
     * DMS
     */
    object ExposureArchiveCompletedEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("exposureArchiveCompleted"))

      /** The name of the file on the DMS.ENG ancillary file store */
      val filenameKey: Key[String] = StringKey.make("filename")

    }

    /** assembly startup metrics */
    object StartupMetricsEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("startupMetrics"))

      /** Assembly initialization start time */
      val initStartTimeKey: Key[TAITime] = TAITimeKey.make("initStartTime")

      /** Assembly initialization completed time */
      val initCompletedTimeKey: Key[TAITime] = TAITimeKey.make("initCompletedTime")

      /** Assembly configuration start time */
      val configureStartTimeKey: Key[TAITime] = TAITimeKey.make("configureStartTime")

      /** Assembly configuration completed time */
      val configureCompletedTimeKey: Key[TAITime] = TAITimeKey.make("configureCompletedTime")

    }

    /** detector temperature set point commanded */
    object TempSetPointCommandedEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("tempSetPointCommanded"))

      /** Current temperature when set point change command sent */
      val startTemperatureKey: Key[Float] = FloatKey.make("startTemperature", Units.degC)

      /** Commanded target temperature */
      val targetTemperatureKey: Key[Float] = FloatKey.make("targetTemperature", Units.degC)

    }

    /** detector temperature set point reached the commanded value */
    object TempSetPointReachedEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("tempSetPointReached"))

      /** Current temperature of the detector */
      val currentTemperatureKey: Key[Float] = FloatKey.make("currentTemperature", Units.degC)

    }

    /** exposure handling metrics */
    object DetectorExposureMetricsEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("detectorExposureMetrics"))

      /** Size of image buffer in bytes. */
      val imageSizeBytesKey: Key[Float] = FloatKey.make("imageSizeBytes", Units.NoUnits)

      /** Integration time of the exposure */
      val integrationTimeKey: Key[Float] = FloatKey.make("integrationTime", Units.second)

      /** Exposure readout completed time */
      val exposureReadoutTimeKey: Key[TAITime] = TAITimeKey.make("exposureReadoutTime")

      /** Start time for image correction algorithms */
      val imageCorrectionsStartTimeKey: Key[TAITime] = TAITimeKey.make("imageCorrectionsStartTime")

      /** Completion time for image correction algorithms */
      val imageCorrectionsCompletedTimeKey: Key[TAITime] = TAITimeKey.make("imageCorrectionsCompletedTime")

      /** Start time for image publishing */
      val imagePublishingStartTimeKey: Key[TAITime] = TAITimeKey.make("imagePublishingStartTime")

      /** Completion time for image publishing */
      val imagePublishingCompletedTimeKey: Key[TAITime] = TAITimeKey.make("imagePublishingCompletedTime")

    }

    /**
     * Sets the camera’s cooling set point and fan speed. This is used to manually cool or warm up the CCD or set a specific
     * temperature for diagnostic/characterization purposes.
     */
    object ConfigDetectorCoolingCommand {
      val commandName: CommandName = CommandName("configDetectorCooling")

      /** Target temperature */
      val temperatureSetPointKey: Key[Float] = FloatKey.make("temperatureSetPoint", Units.degC)

      /** Internal Fan speed */
      val fanSpeedKey: GChoiceKey = ChoiceKey.make("fanSpeed", "OFF", "LOW", "MEDIUM", "HIGH")

    }

    /**
     * Optionally configures the camera’s ROI, binning, shutterMode, cycleMode and gainMode. If a parameter does not appear with
     * the command, the default value in the assembly configuration is used.
     */
    object ConfigDetectorCommand {
      val commandName: CommandName = CommandName("configDetector")

      /** start row of ROI. */
      val roistartRowKey: Key[Int] = IntKey.make("roistartRow", Units.pix)

      /** start col of ROI. */
      val roistartColKey: Key[Int] = IntKey.make("roistartCol", Units.pix)

      /** width of ROI */
      val roiwidthKey: Key[Int] = IntKey.make("roiwidth", Units.pix)

      /** height of ROI */
      val roiheightKey: Key[Int] = IntKey.make("roiheight", Units.pix)

      /** Horizontal Binning in pixels */
      val hBinKey: Key[Int] = IntKey.make("hBin", Units.pix)

      /** Vertical Binning in pixels */
      val vBinKey: Key[Int] = IntKey.make("vBin", Units.pix)

      /** Fastest mode (12-bit) or high dynamic range (16-bit) */
      val gainModeKey: GChoiceKey = ChoiceKey.make("gainMode", "12-BIT", "16-BIT")

    }

    /** Configures the camera to its default configuration and cooling as set in the assembly configuration */
    object SetDefaultConfigurationCommand {
      val commandName: CommandName = CommandName("setDefaultConfiguration")

    }

    /** Takes exposure with detector and performs image pre-processing and publishes the image */
    object TakeAndPublishExposureCommand {
      val commandName: CommandName = CommandName("takeAndPublishExposure")

      /** Integration time. */
      val integrationTimeKey: Key[Float] = FloatKey.make("integrationTime", Units.second)

      /** Fastest mode (12-bit) or high dynamic range (16-bit) */
      val gainModeKey: GChoiceKey = ChoiceKey.make("gainMode", "12-BIT", "16-BIT")

    }

    /** Takes exposure with detector and stores the image in the APS shared disk and DMS */
    object TakeAndStoreExposureCommand {
      val commandName: CommandName = CommandName("takeAndStoreExposure")

      /** Integration time. */
      val integrationTimeKey: Key[Float] = FloatKey.make("integrationTime", Units.second)

      /** Fastest mode (12-bit) or high dynamic range (16-bit) */
      val gainModeKey: GChoiceKey = ChoiceKey.make("gainMode", "12-BIT", "16-BIT")

    }

    /**
     * Takes continuous exposures with detector, performs image preprocessing for each image and publishes each image. The
     * exposures are triggered by software in the assembly. In cases where the APT filter needs to be moved between exposures, or
     * the integration time changed, the commands pauseExposureLoop and restartExposureLoop are used
     */
    object StartExposureLoopCommand {
      val commandName: CommandName = CommandName("startExposureLoop")

      /** Integration time. */
      val integrationTimeKey: Key[Float] = FloatKey.make("integrationTime", Units.second)

      /** Rate at which images are to be published. */
      val rateKey: Key[Float] = FloatKey.make("rate", Units.hertz)

      /** Fastest mode (12-bit) or high dynamic range (16-bit) */
      val gainModeKey: GChoiceKey = ChoiceKey.make("gainMode", "12-BIT", "16-BIT")

    }

    /** Stops the taking of continuous exposures with detector */
    object StopExposureLoopCommand {
      val commandName: CommandName = CommandName("stopExposureLoop")

    }

    /**
     * Pauses the loop that triggers exposures using the software trigger until a restartExposureLoop command is received. The
     * pauseExposureLoop waits for an exposure taking sequence to complete before pausing the loop
     */
    object PauseExposureLoopCommand {
      val commandName: CommandName = CommandName("pauseExposureLoop")

    }

    /** Restarts the loop that triggers exposures using the software trigger. */
    object RestartExposureLoopCommand {
      val commandName: CommandName = CommandName("restartExposureLoop")

    }

    /**
     * Takes a discrete number of continuous exposures and reads them into memory. When the high speed data taking has completed,
     * the APT Detector Assembly reads image data from memory, assembles the data into FITS files according to the chunk size
     * rules in the assemblies configuration and stores the files to the APS Shared Disk and to DMS
     */
    object TakeHighSpeedExposuresCommand {
      val commandName: CommandName = CommandName("takeHighSpeedExposures")

      /** Integration time. */
      val integrationTimeKey: Key[Float] = FloatKey.make("integrationTime", Units.second)

      /** Fastest mode (12-bit) or high dynamic range (16-bit) */
      val gainModeKey: GChoiceKey = ChoiceKey.make("gainMode", "12-BIT", "16-BIT")

      /** Identifier of predefined ROI in the assembly configuration */
      val roiIdentifierKey: Key[Int] = IntKey.make("roiIdentifier", Units.NoUnits)

      /** frame rate (frames/sec). Must be less than the max frame rate associated with the High Speed predefined ROI. */
      val frameRateKey: Key[Int] = IntKey.make("frameRate", Units.NoUnits)

      /** Duration of high speed continuous exposure taking */
      val durationKey: Key[Int] = IntKey.make("duration", Units.second)

    }

    /** Aborts an integrating high speed exposure. Used when aborting a high speed procedure to save time. */
    object AbortHighSpeedExposureCommand {
      val commandName: CommandName = CommandName("abortHighSpeedExposure")

    }

    /** Attempt recovery from fault state using specified strategy */
    object RecoverCommand {
      val commandName: CommandName = CommandName("recover")

      /** Selected recovery action (flush buffers, reset detector, or power cycle) */
      val modeKey: GChoiceKey = ChoiceKey.make("mode", "CLEAR", "RESET", "REBOOT")

      /** If true, resume exposure loop after recovery; defaults to false if omitted */
      val autoResumeKey: Key[Boolean] = BooleanKey.make("autoResume")

    }

    /** Re-initialise the camera and its Micro-Manager device adapter. */
    object ResetCameraCommand {
      val commandName: CommandName = CommandName("resetCamera")

    }

  }

}
