package aps.ics.assembly.icd

// This file contains the API for APS and was generated by the icd-db command.
// DO NOT EDIT.
// See https://github.com/tmtsoftware/icd for more information.

import csw.params.core.generics.KeyType._
import csw.params.commands.CommandName
import csw.params.events._
import csw.prefix.models._
import csw.params.core.generics._
import csw.params.core.models._
import csw.params.core.models.Coords._
import csw.time.core.models._

/**
 * Top level API for: APS
 */
//noinspection ScalaUnusedSymbol
object CalibrationSourceStageKeys {
  val subsystem = "APS"

  /** API for Assembly: APS.ICS.FOC.CalibrationSourceStage */
  object `ICS.FOC.CalibrationSourceStage` {
    val prefix: Prefix = Prefix(Subsystem.APS, "ICS.FOC.CalibrationSourceStage")

    /** CalibrationSourceStage status event */
    object StatusEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("status"))

      /** Current Assembly State */
      val assemblyStateKey: GChoiceKey = ChoiceKey.make("assemblyState", "PRE_HOMED", "OPERATIONAL", "DEGRADED", "FAULTED")

      /** Current HCD State of the HCD that the assembly communicates with */
      val hcdStateKey: GChoiceKey = ChoiceKey.make("hcdState", "UNINITIALIZED", "READY", "FAULTED")

      /** Status of last command */
      val commandStateKey: GChoiceKey = ChoiceKey.make("commandState", "IDLE", "PROCESSING", "ERROR_RECOVERY", "FAILED")

    }

    /** Status information for stage axis */
    object AxisStatusEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("axisStatus"))

      /** The current axis state */
      val axisStateKey: GChoiceKey = ChoiceKey.make("axisState", "LOST", "HOMING", "IDLE", "MOVING", "ERROR")

      /** The current axis position */
      val positionKey: Key[Float] = FloatKey.make("position", Units.millimeter)

      /** The current axis velocity mm/sec */
      val velocityKey: Key[Float] = FloatKey.make("velocity")

      /** True if the axis has been homed */
      val indexedKey: Key[Boolean] = BooleanKey.make("indexed")

      /** True if the axis has reached its target with sufficient accuracy. */
      val inPositionKey: Key[Boolean] = BooleanKey.make("inPosition")

    }

    /** Axis config event, published only when configAxis or configLinearAxis cmd has completed during assembly startup */
    object AxisConfigEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("axisConfig"))

      /** The maxiumum velocity for axis mechanism moves in mm/sec */
      val velocityKey: Key[Float] = FloatKey.make("velocity")

      /** The acceleration used to reach the configured velocity for the axis in mm/sec2 */
      val accelerationKey: Key[Float] = FloatKey.make("acceleration")

      /** The deceleration applied at the end of motor motion for the axis in mm/sec2 */
      val decelerationKey: Key[Float] = FloatKey.make("deceleration")

      /**
       * The offset applied from the physical index switch/mark before setting the axis motor position to 0. Generally a useful
       * starting position (center of motion) for the mechanism
       */
      val indexOffsetKey: Key[Float] = FloatKey.make("indexOffset", Units.millimeter)

      /** The (generally slower) speed used when approaching the axis motor Index Switch for fine accuracy. (mm/sec) */
      val indexSpeedKey: Key[Float] = FloatKey.make("indexSpeed")

      /**
       * TUsed to determine successful completion of demanded moves for the axis. Determined by the needed positioning accuracy of
       * the mechanism
       */
      val inPositionThresholdKey: Key[Float] = FloatKey.make("inPositionThreshold", Units.millimeter)

    }

    /** Event used to communicate that an unexpected condition occured. */
    object ApsAlertEventEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("apsAlertEvent"))

      /** Unhandled errors require filling the message field, whereas other types should fill in the messageId */
      val messageSeverityKey: GChoiceKey = ChoiceKey.make("messageSeverity", "WARN", "ERROR", "UNHANDLED_ERROR")

      /**
       * Sensor originating warnings, errors, controller error codes/messages reported from the controller, and warnings/errors
       * that are a result of calculations
       */
      val sourceKey: GChoiceKey = ChoiceKey.make("source", "SENSOR", "HARDWARE_REPORTED", "CALCULATED")

      /**
       * Key used within the PEAS UI resource properties configuration file that holds all alert messages. Different from
       * procedure events, these alert messages contain placeholders for messageArgs in this alert event.
       */
      val messageIdKey: Key[String] = StringKey.make("messageId")

      /**
       * The message text obtained by the message Id key contains argument placeholders (e.g., {0}, {1}, etc.) that indicate where
       * variable argument values will be inserted. This field provides the ordered list of string values to substitute into the
       * message at the corresponding placeholder positions.
       */
      val messageArgsKey: Key[String] = StringKey.make("messageArgs")

      /** Message supplied by the event source for unhandled errors */
      val messageKey: Key[String] = StringKey.make("message")

    }

    /** Status of light derived from HCD I/O states */
    object InternalLightStatusEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("internalLightStatus"))

      /** status of light on/off state */
      val lightOnKey: GChoiceKey = ChoiceKey.make("lightOn", "ON", "OFF")

      /** light intensity read from galil (% of max) */
      val lightIntensityKey: Key[Float] = FloatKey.make("lightIntensity")

    }

    /** Assembly startup metrics */
    object StartupMetricsEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("startupMetrics"))

      /** Assembly initialization start time */
      val initStartTimeKey: Key[TAITime] = TAITimeKey.make("initStartTime")

      /** Assembly initialization completed time */
      val initCompletedTimeKey: Key[TAITime] = TAITimeKey.make("initCompletedTime")

      /** Assembly axis configuration start time */
      val axisConfigureStartTimeKey: Key[TAITime] = TAITimeKey.make("axisConfigureStartTime")

      /** Assembly axis configuration completed time */
      val axisConfigureCompletedTimeKey: Key[TAITime] = TAITimeKey.make("axisConfigureCompletedTime")

      /** Assembly axis homing started time */
      val axisHomeStartTimeKey: Key[TAITime] = TAITimeKey.make("axisHomeStartTime")

      /** Assembly axis homing completed time */
      val axisHomeCompletedTimeKey: Key[TAITime] = TAITimeKey.make("axisHomeCompletedTime")

    }

    /** Axis motion metrics in response to commanding to a position */
    object AxisMotionMetricsEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("axisMotionMetrics"))

      /** Motion cmd received time */
      val motionCmdReceivedKey: Key[TAITime] = TAITimeKey.make("motionCmdReceived")

      /** Motion cmd completed time */
      val motionCmdCompletedKey: Key[TAITime] = TAITimeKey.make("motionCmdCompleted")

      /** Axis position at the time of cmd receipt */
      val motionStartPositiomKey: Key[Float] = FloatKey.make("motionStartPositiom", Units.millimeter)

      /** Axis position at the time of cmd completion */
      val motionEndPositiomKey: Key[Float] = FloatKey.make("motionEndPositiom", Units.millimeter)

    }

    /**
     * Configures the Galil controller channel for an assembly’s stage/motor. Calls HCD configLinearAxis specifying upper limit,
     * lower limit for linear axes, calls configRotationalAxis for rotational axes, and calls HCD configAxis for each axis,
     * specifying velocity, acceleration, deceleration, index offset, index speed, inPosition threshold.
     */
    object ConfigureCommand {
      val commandName: CommandName = CommandName("configure")

    }

    /**
     * Positions each stage/motor controlled by the assembly to its home position, which is at the center of its range of motion,
     * and sets this as the zero position for the motor. All subsequent moves for a motor are relative to this position, sending a
     * subsequent position command to a motor with value zero (0) will return it to the home position
     */
    object HomeCommand {
      val commandName: CommandName = CommandName("home")

    }

    /**
     * Positions each stage/motor in the assembly to its default positions relative to the home zero position. The default
     * position is the nominal starting position for the assembly. All motion assemblies are moved to their default position when
     * commanding the APS system into “standby mode” during APS system initialization. The default position for each axis of the
     * assembly is part of the assembly configuration
     */
    object MoveToDefaultPositionCommand {
      val commandName: CommandName = CommandName("moveToDefaultPosition")

    }

    /**
     * Sends a stop command to the specified axis controlled by the assembly. This command is used for debugging using the APS
     * engineering user interface.
     */
    object StopCommand {
      val commandName: CommandName = CommandName("stop")

    }

    /**
     * Positions the calibration source stage to place a given optic into the focal plane. If the position is CALIBRATION_SOURCE,
     * the optional parameter “intensity” is used to set the intensity of the source. If the position is not CALIBRATION_SOURCE,
     * the source is turned off.
     */
    object SetOpticAndSourceIntensityCommand {
      val commandName: CommandName = CommandName("setOpticAndSourceIntensity")

      /** The name of the optic to position into the focal plane */
      val opticKey: GChoiceKey = ChoiceKey.make("optic", "CALIBRATION_SOURCE", "ZERNIKE1", "ZERNIKE2", "FIELD_STOP", "OPEN")

      /** The source intensity (% of max). Only used if optic to position is CALIBRATION_SOURCE */
      val sourceIntensityKey: Key[Float] = FloatKey.make("sourceIntensity")

    }

    /** Positions the calibration source stage to place a given optic into the focal plane. */
    object SetOpticCommand {
      val commandName: CommandName = CommandName("setOptic")

      /** The name of the optic to position into the focal plane */
      val opticKey: GChoiceKey = ChoiceKey.make("optic", "CALIBRATION_SOURCE", "ZERNIKE1", "ZERNIKE2", "FIELD_STOP", "OPEN")

    }

    /** Positions the calibration source stage to a given slot number. Used for diagnostic and debugging purposes. */
    object SetSlotCommand {
      val commandName: CommandName = CommandName("setSlot")

      /** The number of the slot to position into the focal plane */
      val slotNumberKey: GChoiceKey = ChoiceKey.make("slotNumber", "1", "2", "3", "4", "5")

    }

    /**
     * Positions the calibration source stage in mm. Used for determining slot positions for each optic, diagnostic and debugging
     * purposes.
     */
    object SetPositionCommand {
      val commandName: CommandName = CommandName("setPosition")

      /** relative offset or absolute positioning from home (0) position */
      val positioningMethodKey: GChoiceKey = ChoiceKey.make("positioningMethod", "ABSOLUTE", "RELATIVE")

      /** the abosolute or relative offset value to move the motor */
      val positionValueKey: Key[Float] = FloatKey.make("positionValue", Units.millimeter)

    }

    /**
     * Sets the intensity of the calibration source. Used during instrument characterization, diagnostic and debugging purposes.
     */
    object SetSourceIntensityCommand {
      val commandName: CommandName = CommandName("setSourceIntensity")

      /** The source intensity (% of max). */
      val sourceIntensityKey: Key[Float] = FloatKey.make("sourceIntensity")

    }

    /** When a command error results in an automatic error recovery process, this command aborts that automatic process. */
    object AbortErrorRecoveryCommand {
      val commandName: CommandName = CommandName("abortErrorRecovery")

    }

  }

}