package aps.ics.assembly.icd

// This file contains the API for APS and was generated by the icd-db command.
// DO NOT EDIT.
// See https://github.com/tmtsoftware/icd for more information.

import csw.params.core.generics.KeyType._
import csw.params.commands.CommandName
import csw.params.events._
import csw.prefix.models._
import csw.params.core.generics._
import csw.params.core.models._
import csw.params.core.models.Coords._
import csw.time.core.models._

/**
 * Top level API for: APS
 */
//noinspection ScalaUnusedSymbol
object FocCollimatorUnitKeys {
  val subsystem = "APS"

  /** API for Assembly: APS.ICS.FOC.CollimatorUnit */
  object `ICS.FOC.CollimatorUnit` {
    val prefix: Prefix = Prefix(Subsystem.APS, "ICS.FOC.CollimatorUnit")

    /** CollimatorUnit status event */
    object StatusEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("status"))

      /** Current Assembly State */
      val assemblyStateKey: GChoiceKey = ChoiceKey.make("assemblyState", "PRE_HOMED", "OPERATIONAL", "DEGRADED", "FAULTED")

      /** Current HCD State of the HCD that the assembly communicates with */
      val hcdStateKey: GChoiceKey = ChoiceKey.make("hcdState", "UNINITIALIZED", "READY", "FAULTED")

      /** Status of last command */
      val commandStateKey: GChoiceKey = ChoiceKey.make("commandState", "IDLE", "PROCESSING", "ERROR_RECOVERY", "FAILED")

    }

    /** Status information for Front Motor axis */
    object FrontAxisStatusEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("frontAxisStatus"))

      /** The current axis state */
      val axisStateKey: GChoiceKey = ChoiceKey.make("axisState", "LOST", "HOMING", "IDLE", "MOVING", "ERROR")

      /** The current axis position */
      val positionKey: Key[Float] = FloatKey.make("position", Units.millimeter)

      /** The current axis velocity mm/sec */
      val velocityKey: Key[Float] = FloatKey.make("velocity")

      /** True if the axis has been homed */
      val indexedKey: Key[Boolean] = BooleanKey.make("indexed")

      /** True if the axis has reached its target with sufficient accuracy. */
      val inPositionKey: Key[Boolean] = BooleanKey.make("inPosition")

    }

    /** Status information for Rear Motor axis */
    object RearAxisStatusEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("rearAxisStatus"))

      /** The current axis state */
      val axisStateKey: GChoiceKey = ChoiceKey.make("axisState", "LOST", "HOMING", "IDLE", "MOVING", "ERROR")

      /** The current axis position */
      val positionKey: Key[Float] = FloatKey.make("position", Units.millimeter)

      /** The current axis velocity mm/sec */
      val velocityKey: Key[Float] = FloatKey.make("velocity")

      /** True if the axis has been homed */
      val indexedKey: Key[Boolean] = BooleanKey.make("indexed")

      /** True if the axis has reached its target with sufficient accuracy. */
      val inPositionKey: Key[Boolean] = BooleanKey.make("inPosition")

    }

    /** Front motor config event, published only when configAxis or configLinearAxis cmd has completed during assembly startup */
    object FrontAxisConfigEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("frontAxisConfig"))

      /** The maximum velocity for axis mechanism moves in mm/sec */
      val velocityKey: Key[Float] = FloatKey.make("velocity")

      /** The acceleration used to reach the configured velocity for the axis in mm/sec2 */
      val accelerationKey: Key[Float] = FloatKey.make("acceleration")

      /** The deceleration applied at the end of motor motion for the axis in mm/sec2 */
      val decelerationKey: Key[Float] = FloatKey.make("deceleration")

      /**
       * The offset applied from the physical index switch/mark before setting the axis motor position to 0. Generally a useful
       * starting position (center of motion) for the mechanism
       */
      val indexOffsetKey: Key[Float] = FloatKey.make("indexOffset", Units.millimeter)

      /** The (generally slower) speed used when approaching the axis motor Index Switch for fine accuracy. (mm/sec) */
      val indexSpeedKey: Key[Float] = FloatKey.make("indexSpeed")

      /**
       * Used to determine successful completion of demanded moves for the axis. Determined by the needed positioning accuracy of
       * the mechanism
       */
      val inPositionThresholdKey: Key[Float] = FloatKey.make("inPositionThreshold", Units.millimeter)

    }

    /** Rear motor config event, published only when configAxis or configLinearAxis cmd has completed during assembly startup */
    object RearAxisConfigEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("rearAxisConfig"))

      /** The maximum velocity for axis mechanism moves in mm/sec */
      val velocityKey: Key[Float] = FloatKey.make("velocity")

      /** The acceleration used to reach the configured velocity for the axis in mm/sec2 */
      val accelerationKey: Key[Float] = FloatKey.make("acceleration")

      /** The deceleration applied at the end of motor motion for the axis in mm/sec2 */
      val decelerationKey: Key[Float] = FloatKey.make("deceleration")

      /**
       * The offset applied from the physical index switch/mark before setting the axis motor position to 0. Generally a useful
       * starting position (center of motion) for the mechanism
       */
      val indexOffsetKey: Key[Float] = FloatKey.make("indexOffset", Units.millimeter)

      /** The (generally slower) speed used when approaching the axis motor Index Switch for fine accuracy. (mm/sec) */
      val indexSpeedKey: Key[Float] = FloatKey.make("indexSpeed")

      /**
       * Used to determine successful completion of demanded moves for the axis. Determined by the needed positioning accuracy of
       * the mechanism
       */
      val inPositionThresholdKey: Key[Float] = FloatKey.make("inPositionThreshold", Units.millimeter)

    }

    /** Event used to communicate that an unexpected condition occurred. */
    object ApsAlertEventEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("apsAlertEvent"))

      /** Unhandled errors require filling the message field, whereas other types should fill in the messageId */
      val messageSeverityKey: GChoiceKey = ChoiceKey.make("messageSeverity", "WARN", "ERROR", "UNHANDLED_ERROR")

      /**
       * Sensor originating warnings, errors, controller error codes/messages reported from the controller, and warnings/errors
       * that are a result of calculations
       */
      val sourceKey: GChoiceKey = ChoiceKey.make("source", "SENSOR", "HARDWARE_REPORTED", "CALCULATED")

      /**
       * Key used within the PEAS UI resource properties configuration file that holds all alert messages. Different from
       * procedure events, these alert messages contain placeholders for messageArgs in this alert event.
       */
      val messageIdKey: Key[String] = StringKey.make("messageId")

      /**
       * The message text obtained by the message Id key contains argument placeholders (e.g., {0}, {1}, etc.) that indicate where
       * variable argument values will be inserted. This field provides the ordered list of string values to substitute into the
       * message at the corresponding placeholder positions.
       */
      val messageArgsKey: Key[String] = StringKey.make("messageArgs")

      /** Message supplied by the event source for unhandled errors */
      val messageKey: Key[String] = StringKey.make("message")

    }

    /** Assembly startup metrics */
    object StartupMetricsEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("startupMetrics"))

      /** Assembly initialization start time */
      val initStartTimeKey: Key[TAITime] = TAITimeKey.make("initStartTime")

      /** Assembly initialization completed time */
      val initCompletedTimeKey: Key[TAITime] = TAITimeKey.make("initCompletedTime")

      /** Assembly front motor configuration start time */
      val frontMotorConfigureStartTimeKey: Key[TAITime] = TAITimeKey.make("frontMotorConfigureStartTime")

      /** Assembly front motor configuration completed time */
      val frontMotorConfigureCompletedTimeKey: Key[TAITime] = TAITimeKey.make("frontMotorConfigureCompletedTime")

      /** Assembly rear motor configuration start time */
      val rearMotorConfigureStartTimeKey: Key[TAITime] = TAITimeKey.make("rearMotorConfigureStartTime")

      /** Assembly rear motor configuration completed time */
      val rearMotorConfigureCompletedTimeKey: Key[TAITime] = TAITimeKey.make("rearMotorConfigureCompletedTime")

      /** Assembly front motor homing started time */
      val frontMotorHomeStartTimeKey: Key[TAITime] = TAITimeKey.make("frontMotorHomeStartTime")

      /** Assembly front motor homing completed time */
      val frontMotorHomeCompletedTimeKey: Key[TAITime] = TAITimeKey.make("frontMotorHomeCompletedTime")

      /** Assembly back motor homing started time */
      val rearMotorHomeStartTimeKey: Key[TAITime] = TAITimeKey.make("rearMotorHomeStartTime")

      /** Assembly back motor homing completed time */
      val rearMotorHomeCompletedTimeKey: Key[TAITime] = TAITimeKey.make("rearMotorHomeCompletedTime")

    }

    /** Front motor motion metrics in response to commanding to a position */
    object FrontMotorMotionMetricsEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("frontMotorMotionMetrics"))

      /** Motion cmd received time */
      val motionCmdReceivedKey: Key[TAITime] = TAITimeKey.make("motionCmdReceived")

      /** Motion cmd completed time */
      val motionCmdCompletedKey: Key[TAITime] = TAITimeKey.make("motionCmdCompleted")

      /** Axis position at the time of cmd receipt */
      val motionStartPositionKey: Key[Float] = FloatKey.make("motionStartPosition", Units.millimeter)

      /** Axis position at the time of cmd completion */
      val motionEndPositionKey: Key[Float] = FloatKey.make("motionEndPosition", Units.millimeter)

    }

    /** Rear motor motion metrics in response to commanding to a position */
    object RearMotorMotionMetricsEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("rearMotorMotionMetrics"))

      /** Motion cmd received time */
      val motionCmdReceivedKey: Key[TAITime] = TAITimeKey.make("motionCmdReceived")

      /** Motion cmd completed time */
      val motionCmdCompletedKey: Key[TAITime] = TAITimeKey.make("motionCmdCompleted")

      /** Axis position at the time of cmd receipt */
      val motionStartPositionKey: Key[Float] = FloatKey.make("motionStartPosition", Units.millimeter)

      /** Axis position at the time of cmd completion */
      val motionEndPositionKey: Key[Float] = FloatKey.make("motionEndPosition", Units.millimeter)

    }

    /**
     * Configures the Galil controller channel for an assembly’s stage/motor. Calls HCD configLinearAxis specifying upper limit,
     * lower limit for linear axes, calls configRotationalAxis for rotational axes, and calls HCD configAxis for each axis,
     * specifying velocity, acceleration, deceleration, index offset, index speed, inPosition threshold.
     */
    object ConfigureCommand {
      val commandName: CommandName = CommandName("configure")

      /** the axis controlling the front or back motor of the Collimator Unit */
      val axisKey: GChoiceKey = ChoiceKey.make("axis", "FRONT_MOTOR", "BACK_MOTOR")

    }

    /**
     * Positions each stage/motor controlled by the assembly to its home position, which is at the center of its range of motion,
     * and sets this as the zero position for the motor. All subsequent moves for a motor are relative to this position, sending a
     * subsequent position command to a motor with value zero (0) will return it to the home position
     */
    object HomeCommand {
      val commandName: CommandName = CommandName("home")

    }

    /**
     * Positions each stage/motor in the assembly to its default positions relative to the home zero position. The default
     * position is the nominal starting position for the assembly. All motion assemblies are moved to their default position when
     * commanding the APS system into “standby mode” during APS system initialization. The default position for each axis of the
     * assembly is part of the assembly configuration
     */
    object MoveToDefaultPositionCommand {
      val commandName: CommandName = CommandName("moveToDefaultPosition")

    }

    /**
     * Sends a stop command to the specified axis controlled by the assembly. This command is used for debugging using the APS
     * engineering user interface.
     */
    object StopCommand {
      val commandName: CommandName = CommandName("stop")

      /** the axis controlling the front or back motor of the Collimator Unit */
      val axisKey: GChoiceKey = ChoiceKey.make("axis", "FRONT_MOTOR", "BACK_MOTOR")

    }

    /** Positions the motors to change the pupil scale by the specific percent scale change. */
    object ChangeScaleCommand {
      val commandName: CommandName = CommandName("changeScale")

      /** The precent scale change. */
      val percentChangeKey: Key[Float] = FloatKey.make("percentChange")

    }

    /** Positions the front motor to the desired offset or absolute position. */
    object PositionFrontAxisCommand {
      val commandName: CommandName = CommandName("positionFrontAxis")

      /** relative offset or absolute positioning from home (0) position */
      val positioningMethodKey: GChoiceKey = ChoiceKey.make("positioningMethod", "ABSOLUTE", "RELATIVE")

      /** the absolute or relative offset value to move the motor */
      val positionValueKey: Key[Float] = FloatKey.make("positionValue", Units.millimeter)

    }

    /** Positions the back motor to the desired offset or absolute position. */
    object PositionRearAxisCommand {
      val commandName: CommandName = CommandName("positionRearAxis")

      /** relative offset or absolute positioning from home (0) position */
      val positioningMethodKey: GChoiceKey = ChoiceKey.make("positioningMethod", "ABSOLUTE", "RELATIVE")

      /** the absolute or relative offset value to move the motor */
      val positionValueKey: Key[Float] = FloatKey.make("positionValue", Units.millimeter)

    }

    /** When a command error results in an automatic error recovery process, this command aborts that automatic process. */
    object AbortErrorRecoveryCommand {
      val commandName: CommandName = CommandName("abortErrorRecovery")

    }

  }

}
