package aps.ics.assembly.icd

// This file contains the API for APS and was generated by the icd-db command.
// DO NOT EDIT.
// See https://github.com/tmtsoftware/icd for more information.

import csw.params.core.generics.KeyType._
import csw.params.commands.CommandName
import csw.params.events._
import csw.prefix.models._
import csw.params.core.generics._
import csw.params.core.models._
import csw.params.core.models.Coords._
import csw.time.core.models._

/**
 * Top level API for: APS
 */
//noinspection ScalaUnusedSymbol
object FocKMirrorKeys {
  val subsystem = "APS"

  /** API for Assembly: APS.ICS.FOC.KMirror */
  object `ICS.FOC.KMirror` {
    val prefix: Prefix = Prefix(Subsystem.APS, "ICS.FOC.KMirror")

    /** K-Mirror status event */
    object StatusEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("status"))

      /** Current Assembly State */
      val assemblyStateKey: GChoiceKey = ChoiceKey.make("assemblyState", "PRE_HOMED", "OPERATIONAL", "DEGRADED", "FAULTED")

      /** Current HCD State of the HCD that the assembly communicates with */
      val hcdStateKey: GChoiceKey = ChoiceKey.make("hcdState", "UNINITIALIZED", "READY", "FAULTED")

      /** Status of last command */
      val commandStateKey: GChoiceKey = ChoiceKey.make("commandState", "IDLE", "PROCESSING", "ERROR_RECOVERY", "FAILED")

      /** The current K-Mirror mode */
      val modeKey: GChoiceKey = ChoiceKey.make("mode", "SLEWING", "TRACKING", "MANUAL")

      /**
       * The slew mode state of the K-Mirror. SLEW_COMPLETE indicates the K-Mirror position has reached the rotational position
       * corresponding to the TCS pupil rotation event value, which during slewing is the expected position when the slew is
       * complete
       */
      val slewModeStateKey: GChoiceKey = ChoiceKey.make("slewModeState", "NOT_SLEWING", "SLEWING", "SLEW_COMPLETE")

      /**
       * The tracking mode state of the K-Mirror. The CONVERGED state is derived by comparing the K-Mirror position read from the
       * Galil HCD currentStateAxis event to the last demand. If this value is within the “Tracking Mode Pupil Rotation In
       * Position Threshold”, the trackingConvergedFlag value is true. The PIT Loop is not started until the CONVERGED state. Once
       * started, the K-Mirror Tracking state transitions to the NOT_CONVERGED_WITH_PIT state and once converged, transitions to
       * the CONVERGED_WITH_PIT state. Once in this state PSH exposures can be taken. If, during a PSH exposure, the tracking
       * state transitions to TRACKING_ERROR, the exposure is marked bad and is retaken
       */
      val trackingModeStateKey: GChoiceKey = ChoiceKey.make(
        "trackingModeState",
        "NOT_TRACKING",
        "NOT_CONVERGED",
        "CONVERGED",
        "NOT_CONVERGED_WITH_PIT",
        "CONVERGED_WITH_PIT",
        "TRACKING_ERROR"
      )

    }

    /** axis status event */
    object AxisStatusEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("axisStatus"))

      /** The current axis state */
      val axisStateKey: GChoiceKey = ChoiceKey.make("axisState", "LOST", "HOMING", "IDLE", "MOVING", "TRACKING", "ERROR")

      /** The current axis position */
      val positionKey: Key[Float] = FloatKey.make("position", Units.degree)

      /** The current axis velocity deg/sec */
      val velocityKey: Key[Float] = FloatKey.make("velocity")

      /** True if the axis has been homed */
      val indexedKey: Key[Boolean] = BooleanKey.make("indexed")

      /** True if the axis has reached its target with sufficient accuracy. */
      val inPositionKey: Key[Boolean] = BooleanKey.make("inPosition")

    }

    /** Axis config event, published only when configAxis or configRotatingAxis cmd has completed during assembly startup */
    object AxisConfigEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("axisConfig"))

      /** The maximum velocity for axis mechanism moves in deg/sec */
      val velocityKey: Key[Float] = FloatKey.make("velocity")

      /** The acceleration used to reach the configured velocity for the axis in deg/sec2 */
      val accelerationKey: Key[Float] = FloatKey.make("acceleration")

      /** The deceleration applied at the end of motor motion for the axis in deg/sec2 */
      val decelerationKey: Key[Float] = FloatKey.make("deceleration")

      /**
       * The offset applied from the physical index switch/mark before setting the axis motor position to 0. Generally a useful
       * starting position (center of motion) for the mechanism
       */
      val indexOffsetKey: Key[Float] = FloatKey.make("indexOffset", Units.degree)

      /** The (generally slower) speed used when approaching the axis motor Index Switch for fine accuracy. (deg/sec) */
      val indexSpeedKey: Key[Float] = FloatKey.make("indexSpeed")

      /**
       * Used to determine successful completion of demanded moves for the axis. Determined by the needed positioning accuracy of
       * the mechanism
       */
      val inPositionThresholdKey: Key[Float] = FloatKey.make("inPositionThreshold", Units.degree)

    }

    /** Event used to communicate a command failure to the user interface and/or Alignment Procedure Sequencer. */
    object ApsCommandFailureEventEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("apsCommandFailureEvent"))

      /** The user readable name of the source assembly or service that published the event */
      val sourceAssemblyKey: Key[String] = StringKey.make("sourceAssembly")

      /** Failure message supplied by the event source. */
      val messageKey: Key[String] = StringKey.make("message")

      /**
       * For failures and errors that have recovery modes (e.g. motion assemblies and detector assemblies) a state for the
       * progress of the recovery is given: started, completed, aborted. For failures that do not support auto recovery, the state
       * is NOT USED.
       */
      val recoveryStateKey: GChoiceKey = ChoiceKey.make("recoveryState", "STARTED", "COMPLETED", "ABORTED", "NOT_USED")

      /** The current auto-recovery retry number. */
      val recoveryRetryIndexKey: Key[Int] = IntKey.make("recoveryRetryIndex", Units.NoUnits)

      /** The total number of auto-recovery retries before recovery is abandoned. */
      val recoveryRetryCountKey: Key[Int] = IntKey.make("recoveryRetryCount", Units.NoUnits)

      /** Indicates if the current retry succeeded or failed. */
      val recoveryRetryStateKey: GChoiceKey = ChoiceKey.make("recoveryRetryState", "FAILURE", "SUCCESS")

    }

    /** K-Mirror tracking errors are outside limits */
    object TrackingErrorEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("trackingError"))

      /** K-Mirror current reported position */
      val positionKey: Key[Float] = FloatKey.make("position", Units.degree)

      /** Calculated demand of expected K-Mirror position */
      val demandKey: Key[Float] = FloatKey.make("demand", Units.degree)

      /** K-Mirror position error threshold */
      val thresholdKey: Key[Float] = FloatKey.make("threshold", Units.degree)

    }

    /** Assembly startup metrics */
    object StartupMetricsEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("startupMetrics"))

      /** Assembly initialization start time */
      val initStartTimeKey: Key[TAITime] = TAITimeKey.make("initStartTime")

      /** Assembly initialization completed time */
      val initCompletedTimeKey: Key[TAITime] = TAITimeKey.make("initCompletedTime")

      /** Assembly axis configuration start time */
      val axisConfigureStartTimeKey: Key[TAITime] = TAITimeKey.make("axisConfigureStartTime")

      /** Assembly axis configuration completed time */
      val axisConfigureCompletedTimeKey: Key[TAITime] = TAITimeKey.make("axisConfigureCompletedTime")

      /** Assembly axis homing started time */
      val axisHomeStartTimeKey: Key[TAITime] = TAITimeKey.make("axisHomeStartTime")

      /** Assembly axis homing completed time */
      val axisHomeCompletedTimeKey: Key[TAITime] = TAITimeKey.make("axisHomeCompletedTime")

    }

    /**
     * K-Mirror axis motion metrics in response to commanding to a position. This event is only published for motion commands in
     * MANUAL mode
     */
    object AxisMotionMetricsEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("axisMotionMetrics"))

      /** Motion cmd received time */
      val motionCmdReceivedKey: Key[TAITime] = TAITimeKey.make("motionCmdReceived")

      /** Motion cmd completed time */
      val motionCmdCompletedKey: Key[TAITime] = TAITimeKey.make("motionCmdCompleted")

      /** Axis position at the time of cmd receipt */
      val motionStartPositionKey: Key[Float] = FloatKey.make("motionStartPosition", Units.degree)

      /** Axis position at the time of cmd completion */
      val motionEndPositionKey: Key[Float] = FloatKey.make("motionEndPosition", Units.degree)

    }

    /** K-Mirror tracking metrics. This event is only published when the K-Mirror is in TRACKING mode. */
    object TrackingMetricsEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("trackingMetrics"))

      /** Difference between computed demand and current K-Mirror position */
      val trackingErrorKey: Key[Float] = FloatKey.make("trackingError", Units.degree)

      /** Flag indicating that the tracking error is within acceptable limits */
      val withinThresholdKey: Key[Boolean] = BooleanKey.make("withinThreshold")

    }

    /**
     * Configures the Galil controller channel for an assembly’s stage/motor. Calls HCD configLinearAxis specifying upper limit,
     * lower limit for linear axes, calls configRotationalAxis for rotational axes, and calls HCD configAxis for each axis,
     * specifying velocity, acceleration, deceleration, index offset, index speed, inPosition threshold.
     */
    object ConfigureCommand {
      val commandName: CommandName = CommandName("configure")

    }

    /**
     * Positions each stage/motor controlled by the assembly to its home position, which is at the center of its range of motion,
     * and sets this as the zero position for the motor. All subsequent moves for a motor are relative to this position, sending a
     * subsequent position command to a motor with value zero (0) will return it to the home position
     */
    object HomeCommand {
      val commandName: CommandName = CommandName("home")

    }

    /**
     * Positions the stage/motor in the assembly to its default position relative to the home zero position. The default position
     * is the nominal starting position for the assembly. All motion assemblies are moved to their default position when
     * commanding the APS system into “standby mode” during APS system initialization. The default position for each axis of the
     * assembly is part of the assembly configuration
     */
    object MoveToDefaultPositionCommand {
      val commandName: CommandName = CommandName("moveToDefaultPosition")

    }

    /**
     * Sends a stop command to the axis controlled by the assembly. This command is used for debugging using the APS engineering
     * user interface.
     */
    object StopCommand {
      val commandName: CommandName = CommandName("stop")

    }

    /**
     * Commands the K-Mirror to a specific position. This command is used to position the K-Mirror manually for diagnostic and
     * debugging purposes
     */
    object PositionKMirrorCommand {
      val commandName: CommandName = CommandName("positionKMirror")

      /** relative offset or absolute positioning from home (0) position */
      val positioningMethodKey: GChoiceKey = ChoiceKey.make("positioningMethod", "ABSOLUTE", "RELATIVE")

      /** the absolute or relative offset value to move the motor */
      val positionValueKey: Key[Float] = FloatKey.make("positionValue", Units.degree)

    }

    /** Sets the operating mode of the K-Mirror. */
    object SetModeCommand {
      val commandName: CommandName = CommandName("setMode")

      /** The desired operating mode. */
      val modeKey: GChoiceKey = ChoiceKey.make("mode", "SLEWING", "TRACKING", "MANUAL")

    }

    /**
     * If in Tracking Mode, this command resets the tracking state to NOT_CONVERGED. In this state, tracking will run without the
     * PIT Loop corrections
     */
    object RestartTrackingCommand {
      val commandName: CommandName = CommandName("restartTracking")

    }

    /** Stores passed PIT correction offset for use in demand calculation. This value is derived from the running PIT Loop. */
    object UpdatePitCorrectionOffsetCommand {
      val commandName: CommandName = CommandName("updatePitCorrectionOffset")

      /** The PIT correction offset demand term value to use when calculating K-Mirror tracking demands. */
      val pitCorrectionOffsetKey: Key[Float] = FloatKey.make("pitCorrectionOffset", Units.degree)

    }

    /**
     * Stores passed rotational offsets in the K-Mirror assembly for use in demand calculation. This value is derived from the
     * most recent pupil registration calibration procedure.
     */
    object UpdatePitToPshOffsetCommand {
      val commandName: CommandName = CommandName("updatePitToPshOffset")

      /** The PIT to PSH offset demand term value to use when calculating K-Mirror tracking demands. */
      val pitToPshRotationOffsetKey: Key[Float] = FloatKey.make("pitToPshRotationOffset", Units.degree)

    }

    /**
     * When a command error results in an automatic error recovery process, this command aborts that automatic process. Only valid
     * when assembly Command State is in the Error Recovery State.
     */
    object AbortErrorRecoveryCommand {
      val commandName: CommandName = CommandName("abortErrorRecovery")

    }

  }

}
