package aps.ics.assembly.icd

// This file contains the API for APS and was generated by the icd-db command.
// DO NOT EDIT.
// See https://github.com/tmtsoftware/icd for more information.

import csw.params.core.generics.KeyType._
import csw.params.commands.CommandName
import csw.params.events._
import csw.prefix.models._
import csw.params.core.generics._
import csw.params.core.models._
import csw.params.core.models.Coords._
import csw.time.core.models._

/**
 * Top level API for: APS
 */
//noinspection ScalaUnusedSymbol
object InsertionStageKeys {
  val subsystem = "APS"

  /** API for Assembly: APS.ICS.STIM.InsertionStage */
  object `ICS.STIM.InsertionStage` {
    val prefix: Prefix = Prefix(Subsystem.APS, "ICS.STIM.InsertionStage")

    /** Stimulus InsertionStage status event */
    object StatusEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("status"))

      /** Current Assembly State */
      val assemblyStateKey: GChoiceKey = ChoiceKey.make("assemblyState", "PRE_HOMED", "OPERATIONAL", "DEGRADED", "FAULTED")

      /** Current HCD State of the HCD that the assembly communicates with */
      val hcdStateKey: GChoiceKey = ChoiceKey.make("hcdState", "UNINITIALIZED", "READY", "FAULTED")

      /** Status of last command */
      val commandStateKey: GChoiceKey = ChoiceKey.make("commandState", "IDLE", "PROCESSING", "ERROR_RECOVERY", "FAILED")

    }

    /** Status information for stage axis */
    object AxisStatusEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("axisStatus"))

      /** The current axis state */
      val axisStateKey: GChoiceKey = ChoiceKey.make("axisState", "LOST", "HOMING", "IDLE", "MOVING", "ERROR")

      /** The current axis position */
      val positionKey: Key[Float] = FloatKey.make("position", Units.millimeter)

      /** The current axis velocity mm/sec */
      val velocityKey: Key[Float] = FloatKey.make("velocity")

      /** True if the axis has been homed */
      val indexedKey: Key[Boolean] = BooleanKey.make("indexed")

      /** True if the axis has reached its target with sufficient accuracy. */
      val inPositionKey: Key[Boolean] = BooleanKey.make("inPosition")

    }

    /** Axis config event, published only when configAxis or configLinearAxis cmd has completed during assembly startup */
    object AxisConfigEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("axisConfig"))

      /** The maximum velocity for axis mechanism moves in mm/sec */
      val velocityKey: Key[Float] = FloatKey.make("velocity")

      /** The acceleration used to reach the configured velocity for the axis in mm/sec2 */
      val accelerationKey: Key[Float] = FloatKey.make("acceleration")

      /** The deceleration applied at the end of motor motion for the axis in mm/sec2 */
      val decelerationKey: Key[Float] = FloatKey.make("deceleration")

      /**
       * The offset applied from the physical index switch/mark before setting the axis motor position to 0. Generally a useful
       * starting position (center of motion) for the mechanism
       */
      val indexOffsetKey: Key[Float] = FloatKey.make("indexOffset", Units.millimeter)

      /** The (generally slower) speed used when approaching the axis motor Index Switch for fine accuracy. (mm/sec) */
      val indexSpeedKey: Key[Float] = FloatKey.make("indexSpeed")

      /**
       * Used to determine successful completion of demanded moves for the axis. Determined by the needed positioning accuracy of
       * the mechanism
       */
      val inPositionThresholdKey: Key[Float] = FloatKey.make("inPositionThreshold", Units.millimeter)

    }

    /** Event used to communicate that an unexpected condition occurred. */
    object ApsAlertEventEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("apsAlertEvent"))

      /** Unhandled errors require filling the message field, whereas other types should fill in the messageId */
      val messageSeverityKey: GChoiceKey = ChoiceKey.make("messageSeverity", "WARN", "ERROR", "UNHANDLED_ERROR")

      /**
       * Sensor originating warnings, errors, controller error codes/messages reported from the controller, and warnings/errors
       * that are a result of calculations
       */
      val sourceKey: GChoiceKey = ChoiceKey.make("source", "SENSOR", "HARDWARE_REPORTED", "CALCULATED")

      /**
       * Key used within the PEAS UI resource properties configuration file that holds all alert messages. Different from
       * procedure events, these alert messages contain placeholders for messageArgs in this alert event.
       */
      val messageIdKey: Key[String] = StringKey.make("messageId")

      /**
       * The message text obtained by the message Id key contains argument placeholders (e.g., {0}, {1}, etc.) that indicate where
       * variable argument values will be inserted. This field provides the ordered list of string values to substitute into the
       * message at the corresponding placeholder positions.
       */
      val messageArgsKey: Key[String] = StringKey.make("messageArgs")

      /** Message supplied by the event source for unhandled errors */
      val messageKey: Key[String] = StringKey.make("message")

    }

    /** Assembly startup metrics */
    object StartupMetricsEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("startupMetrics"))

      /** Assembly initialization start time */
      val initStartTimeKey: Key[TAITime] = TAITimeKey.make("initStartTime")

      /** Assembly initialization completed time */
      val initCompletedTimeKey: Key[TAITime] = TAITimeKey.make("initCompletedTime")

      /** Assembly axis configuration start time */
      val axisConfigureStartTimeKey: Key[TAITime] = TAITimeKey.make("axisConfigureStartTime")

      /** Assembly axis configuration completed time */
      val axisConfigureCompletedTimeKey: Key[TAITime] = TAITimeKey.make("axisConfigureCompletedTime")

      /** Assembly axis homing started time */
      val axisHomeStartTimeKey: Key[TAITime] = TAITimeKey.make("axisHomeStartTime")

      /** Assembly axis homing completed time */
      val axisHomeCompletedTimeKey: Key[TAITime] = TAITimeKey.make("axisHomeCompletedTime")

    }

    /** Axis motion metrics in response to commanding to a position */
    object AxisMotionMetricsEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("axisMotionMetrics"))

      /** Motion cmd received time */
      val motionCmdReceivedKey: Key[TAITime] = TAITimeKey.make("motionCmdReceived")

      /** Motion cmd completed time */
      val motionCmdCompletedKey: Key[TAITime] = TAITimeKey.make("motionCmdCompleted")

      /** Axis position at the time of cmd receipt */
      val motionStartPositionKey: Key[Float] = FloatKey.make("motionStartPosition", Units.millimeter)

      /** Axis position at the time of cmd completion */
      val motionEndPositionKey: Key[Float] = FloatKey.make("motionEndPosition", Units.millimeter)

    }

    /**
     * Configures the Galil controller channel for an assembly’s stage/motor. Calls HCD configLinearAxis specifying upper limit,
     * lower limit for linear axes, calls configRotationalAxis for rotational axes, and calls HCD configAxis for each axis,
     * specifying velocity, acceleration, deceleration, index offset, index speed, inPosition threshold.
     */
    object ConfigureCommand {
      val commandName: CommandName = CommandName("configure")

    }

    /**
     * Positions each stage/motor controlled by the assembly to its home position, which is at the center of its range of motion,
     * and sets this as the zero position for the motor. All subsequent moves for a motor are relative to this position, sending a
     * subsequent position command to a motor with value zero (0) will return it to the home position
     */
    object HomeCommand {
      val commandName: CommandName = CommandName("home")

    }

    /**
     * Positions each stage/motor in the assembly to its default positions relative to the home zero position. The default
     * position is the nominal starting position for the assembly. All motion assemblies are moved to their default position when
     * commanding the APS system into “standby mode” during APS system initialization. The default position for each axis of the
     * assembly is part of the assembly configuration
     */
    object MoveToDefaultPositionCommand {
      val commandName: CommandName = CommandName("moveToDefaultPosition")

    }

    /**
     * Sends a stop command to the axis controlled by the assembly. This command is used for debugging using the APS engineering
     * user interface.
     */
    object StopCommand {
      val commandName: CommandName = CommandName("stop")

    }

    /** Commands the stimulus insertion stage to select light source from sky or stimulus */
    object SelectSourceCommand {
      val commandName: CommandName = CommandName("selectSource")

      /** The selected light source. */
      val lightSourceKey: GChoiceKey = ChoiceKey.make("lightSource", "SKY", "STIMULUS")

    }

    /**
     * Positions the stage using either the offset or absolute positioning. Used for diagnostic troubleshooting and Zernike
     * Wavefront sensing.
     */
    object PositionStageCommand {
      val commandName: CommandName = CommandName("positionStage")

      /** The method used to position the stage. */
      val positionMethodKey: GChoiceKey = ChoiceKey.make("positionMethod", "ABSOLUTE", "RELATIVE")

      /** The absolute or offset value to move the stage. */
      val valueKey: Key[Float] = FloatKey.make("value", Units.millimeter)

    }

    /**
     * When a command error results in an automatic error recovery process, this command aborts that automatic process. Only valid
     * when assembly Command State is in the Error Recovery State.
     */
    object AbortErrorRecoveryCommand {
      val commandName: CommandName = CommandName("abortErrorRecovery")

    }

  }

}
