package aps.ics.assembly.icd

// This file contains the API for APS and was generated by the icd-db command.
// DO NOT EDIT.
// See https://github.com/tmtsoftware/icd for more information.

import csw.params.core.generics.KeyType._
import csw.params.commands.CommandName
import csw.params.events._
import csw.prefix.models._
import csw.params.core.generics._
import csw.params.core.models._
import csw.params.core.models.Coords._
import csw.time.core.models._

/**
 * Top level API for: APS
 */
//noinspection ScalaUnusedSymbol
object PitDetectorKeys {
  val subsystem = "APS"

  /** API for Assembly: APS.ICS.PIT.Detector */
  object `ICS.PIT.Detector` {
    val prefix: Prefix = Prefix(Subsystem.APS, "ICS.PIT.Detector")

    /** PIT Detector status event. This is event is published at 1 Hz */
    object StatusEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("status"))

      /** Current Assembly State */
      val assemblyStateKey: GChoiceKey = ChoiceKey.make("assemblyState", "READY", "DEGRADED", "FAULTED")

      /** Cooling subsystem health classification (mapped from device-specific states) */
      val coolingHealthKey: GChoiceKey = ChoiceKey.make("coolingHealth", "Good", "Degraded", "Bad")

      /** Camera detected and initialized */
      val cameraPresentKey: Key[Boolean] = BooleanKey.make("cameraPresent")

      /** Camera acquisition state */
      val cameraAcquisitionStateKey: GChoiceKey =
        ChoiceKey.make("cameraAcquisitionState", "IDLE", "BUSY", "STREAMING", "PAUSED", "FAULT", "RECOVERING")

    }

    /** PIT Detector temperatureStatus event. The parameter values can change more often than we need to publish them (0.1 Hz) */
    object TemperatureStatusEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("temperatureStatus"))

      /** The current temperature of the detector */
      val detectorTemperatureKey: Key[Float] = FloatKey.make("detectorTemperature", Units.degC)

      /** Configured temperature set point */
      val temperatureSetPointKey: Key[Float] = FloatKey.make("temperatureSetPoint", Units.degC)

    }

    /**
     * PIT Detector setupStatus event. These parameters change only at the start of the PIT Loop or when setting setting the
     * detector temp and are only published when one or more changes value
     */
    object SetupStatusEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("setupStatus"))

      /** The buffer size in bytes required to store the data for one frame. */
      val imageSizeKey: Key[Int] = IntKey.make("imageSize", Units.NoUnits)

      /** Current acquisition mode. */
      val acquisitionModeKey: GChoiceKey = ChoiceKey.make("acquisitionMode", "SINGLE", "BURST", "LOOP")

      /** Memory strategy used for data capture. */
      val bufferModelKey: GChoiceKey = ChoiceKey.make("bufferModel", "SINGLE", "CONTAINER", "RING")

      /** Continuous mode frame rate. */
      val frameRateKey: Key[Float] = FloatKey.make("frameRate", Units.hertz)

      /** Shared-memory location of the active buffer. */
      val pathKey: Key[String] = StringKey.make("path", Units.NoUnits)

      /** The currently configured integration time. */
      val integrationTimeKey: Key[Float] = FloatKey.make("integrationTime", Units.millisecond)

      /** Starting row of region of interest */
      val roiStartRowKey: Key[Int] = IntKey.make("roiStartRow", Units.pix)

      /** Starting col of region of interest */
      val roiStartColKey: Key[Int] = IntKey.make("roiStartCol", Units.pix)

      /** Number of rows in the region of interest */
      val roiHeightKey: Key[Int] = IntKey.make("roiHeight", Units.pix)

      /** Number of columns in the region of interest */
      val roiWidthKey: Key[Int] = IntKey.make("roiWidth", Units.pix)

      /** Horizontal Binning in pixels */
      val hBinKey: Key[Int] = IntKey.make("hBin", Units.pix)

      /** Vertical Binning in pixels */
      val vBinKey: Key[Int] = IntKey.make("vBin", Units.pix)

    }

    /**
     * PIT Detector configStatus event. These parameters typically do not change value during normal operations, but might change
     * during instrument characterization and AIV. Only published on when the assembly sends the configureDetector command to the
     * Teledyne HCD
     */
    object ConfigStatusEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("configStatus"))

      /**
       * The current gain processing mode. HDR combines High and Low gain exposures to increase dynamic range at the cost of
       * readout speed.
       */
      val analogGainKey: GChoiceKey = ChoiceKey.make("analogGain", "LOW", "HIGH", "HDR")

      /** Resolution of pixel digitization in bits/pixel. */
      val bitDepthKey: GChoiceKey = ChoiceKey.make("bitDepth", "14-bit", "16-bit")

      /** The current shutter control mode. */
      val shutterModeKey: GChoiceKey = ChoiceKey.make("shutterMode", "Rolling", "Global")

      /** Correlated Multisampling Mode (CMS). When enabled, CMS will produce the lowest read noise. */
      val cmsKey: GChoiceKey = ChoiceKey.make("cms", "ON", "OFF")

    }

    /** Event used to communicate a command failure to the user interface and/or Alignment Procedure Sequencer. */
    object ApsCommandFailureEventEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("apsCommandFailureEvent"))

      /** The user readable name of the source assembly or service that published the event */
      val sourceAssemblyKey: Key[String] = StringKey.make("sourceAssembly")

      /** Failure message supplied by the event source. */
      val messageKey: Key[String] = StringKey.make("message")

      /**
       * For failures and errors that have recovery modes (e.g. motion assemblies and detector assemblies) a state for the
       * progress of the recovery is given: started, completed, aborted. For failures that do not support auto recovery, the state
       * is NOT USED.
       */
      val recoveryStateKey: GChoiceKey = ChoiceKey.make("recoveryState", "STARTED", "COMPLETED", "ABORTED", "NOT_USED")

      /** The current auto-recovery retry number. */
      val recoveryRetryIndexKey: Key[Int] = IntKey.make("recoveryRetryIndex", Units.NoUnits)

      /** The total number of auto-recovery retries before recovery is abandoned. */
      val recoveryRetryCountKey: Key[Int] = IntKey.make("recoveryRetryCount", Units.NoUnits)

      /** Indicates if the current retry succeeded or failed. */
      val recoveryRetryStateKey: GChoiceKey = ChoiceKey.make("recoveryRetryState", "FAILURE", "SUCCESS")

    }

    /**
     * PIT Detector exposure store completed event. Used to notify APS-PEAS of incoming images just stored on the APS Shared disk
     */
    object ExposureStoreCompletedEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("exposureStoreCompleted"))

      /** TThe name of the file on the APS Shared Disk */
      val filenameKey: Key[String] = StringKey.make("filename")

    }

    /**
     * PIT Detector exposure archive completed event. Used to update APS-PEAS Exposure Service of images that have been stored to
     * DMS
     */
    object ExposureArchiveCompletedEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("exposureArchiveCompleted"))

      /** The name of the file on the DMS.ENG ancillary file store */
      val filenameKey: Key[String] = StringKey.make("filename")

    }

    /** assembly startup metrics */
    object StartupMetricsEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("startupMetrics"))

      /** Assembly initialization start time */
      val initStartTimeKey: Key[TAITime] = TAITimeKey.make("initStartTime")

      /** Assembly initialization completed time */
      val initCompletedTimeKey: Key[TAITime] = TAITimeKey.make("initCompletedTime")

      /** Assembly configuration start time */
      val configureStartTimeKey: Key[TAITime] = TAITimeKey.make("configureStartTime")

      /** Assembly configuration completed time */
      val configureCompletedTimeKey: Key[TAITime] = TAITimeKey.make("configureCompletedTime")

    }

    /** detector temperature set point commanded */
    object TempSetPointCommandedEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("tempSetPointCommanded"))

      /** Current temperature when set point change command sent */
      val startTemperatureKey: Key[Float] = FloatKey.make("startTemperature", Units.degC)

      /** Commanded target temperature */
      val targetTemperatureKey: Key[Float] = FloatKey.make("targetTemperature", Units.degC)

    }

    /** detector temperature set point reached the commanded value */
    object TempSetPointReachedEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("tempSetPointReached"))

      /** Current temperature of the detector */
      val currentTemperatureKey: Key[Float] = FloatKey.make("currentTemperature", Units.degC)

    }

    /** exposure handling metrics */
    object DetectorExposureMetricsEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("detectorExposureMetrics"))

      /** Size of image buffer in bytes. */
      val imageSizeBytesKey: Key[Float] = FloatKey.make("imageSizeBytes", Units.NoUnits)

      /** Integration time of the exposure */
      val integrationTimeKey: Key[Float] = FloatKey.make("integrationTime", Units.second)

      /** Exposure readout completed time */
      val exposureReadoutTimeKey: Key[TAITime] = TAITimeKey.make("exposureReadoutTime")

      /** Start time for image correction algorithms */
      val imageCorrectionsStartTimeKey: Key[TAITime] = TAITimeKey.make("imageCorrectionsStartTime")

      /** Completion time for image correction algorithms */
      val imageCorrectionsCompletedTimeKey: Key[TAITime] = TAITimeKey.make("imageCorrectionsCompletedTime")

      /** Start time for image publishing */
      val imagePublishingStartTimeKey: Key[TAITime] = TAITimeKey.make("imagePublishingStartTime")

      /** Completion time for image publishing */
      val imagePublishingCompletedTimeKey: Key[TAITime] = TAITimeKey.make("imagePublishingCompletedTime")

    }

    /**
     * Sets the camera’s cooling set point. This is used to manually cool or warm up the CCD or set a specific temperature for
     * diagnostic/characterization purposes.
     */
    object ConfigureDetectorCoolingCommand {
      val commandName: CommandName = CommandName("configureDetectorCooling")

      /** Target temperature */
      val temperatureSetPointKey: Key[Float] = FloatKey.make("temperatureSetPoint", Units.degC)

    }

    /**
     * COptionally configures the camera’s ROI, gain, readout (14 or 16 bit), rolling or global shutter, and correlated
     * multisampling mode (lowest read noise, only available with rolling shutter, 16-bit readout). If an optional parameter does
     * not appear in the command, the corresponding value from the assembly configuration is used.
     */
    object ConfigureDetectorCommand {
      val commandName: CommandName = CommandName("configureDetector")

      /** start row of ROI. */
      val roiStartRowKey: Key[Int] = IntKey.make("roiStartRow", Units.pix)

      /** start col of ROI. */
      val rotStartColKey: Key[Int] = IntKey.make("rotStartCol", Units.pix)

      /** width of ROI */
      val roiWidthKey: Key[Int] = IntKey.make("roiWidth", Units.pix)

      /** height of ROI */
      val roiHeightKey: Key[Int] = IntKey.make("roiHeight", Units.pix)

      /** Horizontal Binning in pixels */
      val hBinKey: Key[Int] = IntKey.make("hBin", Units.pix)

      /** Vertical Binning in pixels */
      val vBinKey: Key[Int] = IntKey.make("vBin", Units.pix)

      /** Analog gain */
      val analogGainModeKey: GChoiceKey = ChoiceKey.make("analogGainMode", "LOW", "HIGH", "HDR")

      /** 14 or 16-bit readout */
      val bitDepthKey: GChoiceKey = ChoiceKey.make("bitDepth", "14-bit", "16-bit")

      /** rolling or global readout */
      val shutterModeKey: GChoiceKey = ChoiceKey.make("shutterMode", "ROLLING", "GLOBAL")

      /** rCorrelated Multisampling Mode */
      val cmsKey: GChoiceKey = ChoiceKey.make("cms", "ON", "OFF")

    }

    /** Configures the camera to its default configuration and cooling as set in the assembly configuration */
    object SetDefaultConfigurationCommand {
      val commandName: CommandName = CommandName("setDefaultConfiguration")

    }

    /**
     * Takes exposure with PIT detector and coverts to float array data in memory mapped file. When the command is completed, the
     * data is retrieved by the ICS Computation assembly from the memory mapped file for pupil registration processing
     */
    object TakeExposureCommand {
      val commandName: CommandName = CommandName("takeExposure")

      /** Integration time. */
      val integrationTimeKey: Key[Float] = FloatKey.make("integrationTime", Units.second)

      /** Analog gain */
      val analogGainModeKey: GChoiceKey = ChoiceKey.make("analogGainMode", "LOW", "HIGH", "HDR")

    }

    /**
     * Stores an exposure in memory mapped file as a FITS file on the APS Shared Disk and DMS. When the file is stored, the
     * pit.Detector.exposureStoreCompleted event is published to inform PEAS that image data is available
     */
    object StoreExposureCommand {
      val commandName: CommandName = CommandName("storeExposure")

    }

    /** A combination of takeExposure followed by storeExposure */
    object TakeAndStoreExposureCommand {
      val commandName: CommandName = CommandName("takeAndStoreExposure")

      /** Integration time. */
      val integrationTimeKey: Key[Float] = FloatKey.make("integrationTime", Units.second)

      /** Analog gain */
      val analogGainModeKey: GChoiceKey = ChoiceKey.make("analogGainMode", "LOW", "HIGH", "HDR")

    }

    /** Aborts an integrating PIT exposure. Used within the sequencer abortHandler to save time when aborting a procedure. */
    object AbortExposureCommand {
      val commandName: CommandName = CommandName("abortExposure")

    }

    /** Attempt recovery from fault state using specified strategy */
    object RecoverCommand {
      val commandName: CommandName = CommandName("recover")

      /** Selected recovery action (flush buffers, reset detector, or power cycle) */
      val modeKey: GChoiceKey = ChoiceKey.make("mode", "CLEAR", "RESET", "REBOOT")

      /** If true, resume exposure loop after recovery; defaults to false if omitted */
      val autoResumeKey: Key[Boolean] = BooleanKey.make("autoResume")

    }

    /** Re-initialise the camera and its Micro-Manager device adapter. */
    object ResetCameraCommand {
      val commandName: CommandName = CommandName("resetCamera")

    }

  }

}
