package aps.ics.assembly.icd

// This file contains the API for APS and was generated by the icd-db command.
// DO NOT EDIT.
// See https://github.com/tmtsoftware/icd for more information.

import csw.params.core.generics.KeyType._
import csw.params.commands.CommandName
import csw.params.events._
import csw.prefix.models._
import csw.params.core.generics._
import csw.params.core.models._
import csw.params.core.models.Coords._
import csw.time.core.models._

/**
 * Top level API for: APS
 */
//noinspection ScalaUnusedSymbol
object PitFilterWheelKeys {
  val subsystem = "APS"

  /** API for Assembly: APS.ICS.PIT.FilterWheel */
  object `ICS.PIT.FilterWheel` {
    val prefix: Prefix = Prefix(Subsystem.APS, "ICS.PIT.FilterWheel")

    /** PIT FilterWheel status event */
    object StatusEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("status"))

      /** Current Assembly State */
      val assemblyStateKey: GChoiceKey = ChoiceKey.make("assemblyState", "PRE_HOMED", "OPERATIONAL", "DEGRADED", "FAULTED")

      /** Current HCD State of the HCD that the assembly communicates with */
      val hcdStateKey: GChoiceKey = ChoiceKey.make("hcdState", "UNINITIALIZED", "READY", "FAULTED")

      /** Status of last command */
      val commandStateKey: GChoiceKey = ChoiceKey.make("commandState", "IDLE", "PROCESSING", "ERROR_RECOVERY", "FAILED")

    }

    /** PIT FilterWheel axis status event */
    object AxisStatusEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("axisStatus"))

      /** The current axis state */
      val axisStateKey: GChoiceKey = ChoiceKey.make("axisState", "LOST", "HOMING", "IDLE", "MOVING", "ERROR")

      /** The current axis position */
      val positionKey: Key[Float] = FloatKey.make("position", Units.degree)

      /** The current axis velocity deg/sec */
      val velocityKey: Key[Float] = FloatKey.make("velocity")

      /** True if the axis has been homed */
      val indexedKey: Key[Boolean] = BooleanKey.make("indexed")

      /** True if the axis has reached its target with sufficient accuracy. */
      val inPositionKey: Key[Boolean] = BooleanKey.make("inPosition")

      /** The current wheel position */
      val wheelPositionNumKey: Key[Int] = IntKey.make("wheelPositionNum")

    }

    /**
     * PIT FilterWheel axis config event, published only when configAxis or configRotatingAxis cmd has completed during assembly
     * startup
     */
    object AxisConfigEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("axisConfig"))

      /** The maximum velocity for axis mechanism moves in deg/sec */
      val velocityKey: Key[Float] = FloatKey.make("velocity")

      /** The acceleration used to reach the configured velocity for the axis in deg/sec2 */
      val accelerationKey: Key[Float] = FloatKey.make("acceleration")

      /** The deceleration applied at the end of motor motion for the axis in deg/sec2 */
      val decelerationKey: Key[Float] = FloatKey.make("deceleration")

      /**
       * The offset applied from the physical index switch/mark before setting the axis motor position to 0. Generally a useful
       * starting position (center of motion) for the mechanism
       */
      val indexOffsetKey: Key[Float] = FloatKey.make("indexOffset", Units.degree)

      /** The (generally slower) speed used when approaching the axis motor Index Switch for fine accuracy. (deg/sec) */
      val indexSpeedKey: Key[Float] = FloatKey.make("indexSpeed")

      /**
       * Used to determine successful completion of demanded moves for the axis. Determined by the needed positioning accuracy of
       * the mechanism
       */
      val inPositionThresholdKey: Key[Float] = FloatKey.make("inPositionThreshold", Units.degree)

    }

    /** Event used to communicate a command failure to the user interface and/or Alignment Procedure Sequencer. */
    object ApsCommandFailureEventEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("apsCommandFailureEvent"))

      /** The user readable name of the source assembly or service that published the event */
      val sourceAssemblyKey: Key[String] = StringKey.make("sourceAssembly")

      /** Failure message supplied by the event source. */
      val messageKey: Key[String] = StringKey.make("message")

      /**
       * For failures and errors that have recovery modes (e.g. motion assemblies and detector assemblies) a state for the
       * progress of the recovery is given: started, completed, aborted. For failures that do not support auto recovery, the state
       * is NOT USED.
       */
      val recoveryStateKey: GChoiceKey = ChoiceKey.make("recoveryState", "STARTED", "COMPLETED", "ABORTED", "NOT_USED")

      /** The current auto-recovery retry number. */
      val recoveryRetryIndexKey: Key[Int] = IntKey.make("recoveryRetryIndex", Units.NoUnits)

      /** The total number of auto-recovery retries before recovery is abandoned. */
      val recoveryRetryCountKey: Key[Int] = IntKey.make("recoveryRetryCount", Units.NoUnits)

      /** Indicates if the current retry succeeded or failed. */
      val recoveryRetryStateKey: GChoiceKey = ChoiceKey.make("recoveryRetryState", "FAILURE", "SUCCESS")

    }

    /** Assembly startup metrics */
    object StartupMetricsEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("startupMetrics"))

      /** Assembly initialization start time */
      val initStartTimeKey: Key[TAITime] = TAITimeKey.make("initStartTime")

      /** Assembly initialization completed time */
      val initCompletedTimeKey: Key[TAITime] = TAITimeKey.make("initCompletedTime")

      /** Assembly axis configuration start time */
      val axisConfigureStartTimeKey: Key[TAITime] = TAITimeKey.make("axisConfigureStartTime")

      /** Assembly axis configuration completed time */
      val axisConfigureCompletedTimeKey: Key[TAITime] = TAITimeKey.make("axisConfigureCompletedTime")

      /** Assembly axis homing started time */
      val axisHomeStartTimeKey: Key[TAITime] = TAITimeKey.make("axisHomeStartTime")

      /** Assembly axis homing completed time */
      val axisHomeCompletedTimeKey: Key[TAITime] = TAITimeKey.make("axisHomeCompletedTime")

    }

    /** Axis motion metrics in response to commanding to a position */
    object AxisMotionMetricsEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("axisMotionMetrics"))

      /** Motion cmd received time */
      val motionCmdReceivedKey: Key[TAITime] = TAITimeKey.make("motionCmdReceived")

      /** Motion cmd completed time */
      val motionCmdCompletedKey: Key[TAITime] = TAITimeKey.make("motionCmdCompleted")

      /** Axis position at the time of cmd receipt */
      val motionStartPositionKey: Key[Float] = FloatKey.make("motionStartPosition", Units.degree)

      /** Axis position at the time of cmd completion */
      val motionEndPositionKey: Key[Float] = FloatKey.make("motionEndPosition", Units.degree)

    }

    /**
     * Positions the wheel motor to home position, which is wheel position #1. All subsequent moves for a motor are relative to
     * this position, sending a subsequent position command to a motor with value zero (0) will return it to the home position.
     */
    object HomeCommand {
      val commandName: CommandName = CommandName("home")

    }

    /**
     * Positions the filter wheel to its default position. The default position is the nominal starting position for the assembly.
     * All motion assemblies are moved to their default position when commanding the APS system into “standby mode” during APS
     * system initialization.</p> <p>The default position is part of the assembly configuration.
     */
    object MoveToDefaultPositionCommand {
      val commandName: CommandName = CommandName("moveToDefaultPosition")

    }

    /**
     * Positions the wheel in degrees or motor in steps. Used for command calibration, diagnostic and debugging purposes. Sending
     * this command while the wheel detent is extended will fail command validation.
     */
    object PositionMotorCommand {
      val commandName: CommandName = CommandName("positionMotor")

      /** The method used to position the motor. */
      val positioningMethodKey: GChoiceKey = ChoiceKey.make("positioningMethod", "ABSOLUTE", "RELATIVE")

      /** Specifies which is being positioned, wheel or motor. */
      val positionTargetKey: GChoiceKey = ChoiceKey.make("positionTarget", "WHEEL", "MOTOR")

      /** The desired wheel position. */
      val wheelPositionKey: Key[Float] = FloatKey.make("wheelPosition", Units.degree)

      /** The desired motor position. */
      val motorPositionKey: Key[Int] = IntKey.make("motorPosition", Units.count)

    }

    /** Selects a filter to position into the light beam. */
    object SelectFilterCommand {
      val commandName: CommandName = CommandName("selectFilter")

      /** The name of the filter to position into the beam */
      val filterKey: GChoiceKey = ChoiceKey.make("filter", "F890N", "F891N", "F850M", "F750W", "F810N", "F630N", "F865N")

    }

    /** Commands the filter wheel to a place a specified filter position number into the beam. */
    object PositionWheelCommand {
      val commandName: CommandName = CommandName("positionWheel")

      /** The wheel position number to place into the beam */
      val positionNumberKey: GChoiceKey = ChoiceKey.make("positionNumber", "1", "2", "3", "4", "5", "6", "7")

    }

    /**
     * When a command error results in an automatic error recovery process, this command aborts that automatic process. Only valid
     * when assembly Command State is in the Error Recovery State.
     */
    object AbortErrorRecoveryCommand {
      val commandName: CommandName = CommandName("abortErrorRecovery")

    }

  }

}
