package aps.ics.assembly.icd

// This file contains the API for APS and was generated by the icd-db command.
// DO NOT EDIT.
// See https://github.com/tmtsoftware/icd for more information.

import csw.params.core.generics.KeyType._
import csw.params.commands.CommandName
import csw.params.events._
import csw.prefix.models._
import csw.params.core.generics._
import csw.params.core.models._
import csw.params.core.models.Coords._
import csw.time.core.models._

/**
 * Top level API for: APS
 */
//noinspection ScalaUnusedSymbol
object StimFiberSourceStageKeys {
  val subsystem = "APS"

  /** API for Assembly: APS.ICS.STIM.FiberSourceStage */
  object `ICS.STIM.FiberSourceStage` {
    val prefix: Prefix = Prefix(Subsystem.APS, "ICS.STIM.FiberSourceStage")

    /** FiberSourceStage status event */
    object StatusEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("status"))

      /** Current Assembly State */
      val assemblyStateKey: GChoiceKey = ChoiceKey.make("assemblyState", "PRE_HOMED", "OPERATIONAL", "DEGRADED", "FAULTED")

      /** Current HCD State of the HCD that the assembly communicates with */
      val hcdStateKey: GChoiceKey = ChoiceKey.make("hcdState", "UNINITIALIZED", "READY", "FAULTED")

      /** Status of last command */
      val commandStateKey: GChoiceKey = ChoiceKey.make("commandState", "IDLE", "PROCESSING", "ERROR_RECOVERY", "FAILED")

    }

    /** Status information for X axis */
    object XAxisStatusEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("xAxisStatus"))

      /** The current axis state */
      val axisStateKey: GChoiceKey = ChoiceKey.make("axisState", "LOST", "HOMING", "IDLE", "MOVING", "ERROR")

      /** The current axis position */
      val positionKey: Key[Float] = FloatKey.make("position", Units.millimeter)

      /** The current axis velocity mm/sec */
      val velocityKey: Key[Float] = FloatKey.make("velocity")

      /** True if the axis has been homed */
      val indexedKey: Key[Boolean] = BooleanKey.make("indexed")

      /** True if the axis has reached its target with sufficient accuracy. */
      val inPositionKey: Key[Boolean] = BooleanKey.make("inPosition")

    }

    /** Status information for Y axis */
    object YAxisStatusEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("yAxisStatus"))

      /** The current axis state */
      val axisStateKey: GChoiceKey = ChoiceKey.make("axisState", "LOST", "HOMING", "IDLE", "MOVING", "ERROR")

      /** The current axis position */
      val positionKey: Key[Float] = FloatKey.make("position", Units.millimeter)

      /** The current axis velocity mm/sec */
      val velocityKey: Key[Float] = FloatKey.make("velocity")

      /** True if the axis has been homed */
      val indexedKey: Key[Boolean] = BooleanKey.make("indexed")

      /** True if the axis has reached its target with sufficient accuracy. */
      val inPositionKey: Key[Boolean] = BooleanKey.make("inPosition")

    }

    /** Status information for Z axis */
    object ZAxisStatusEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("zAxisStatus"))

      /** The current axis state */
      val axisStateKey: GChoiceKey = ChoiceKey.make("axisState", "LOST", "HOMING", "IDLE", "MOVING", "ERROR")

      /** The current axis position */
      val positionKey: Key[Float] = FloatKey.make("position", Units.millimeter)

      /** The current axis velocity mm/sec */
      val velocityKey: Key[Float] = FloatKey.make("velocity")

      /** True if the axis has been homed */
      val indexedKey: Key[Boolean] = BooleanKey.make("indexed")

      /** True if the axis has reached its target with sufficient accuracy. */
      val inPositionKey: Key[Boolean] = BooleanKey.make("inPosition")

    }

    /** X axis config event, published only when configAxis or configLinearAxis cmd has completed during assembly startup */
    object XAxisConfigEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("xAxisConfig"))

      /** The maximum velocity for axis mechanism moves in mm/sec */
      val velocityKey: Key[Float] = FloatKey.make("velocity")

      /** The acceleration used to reach the configured velocity for the axis in mm/sec2 */
      val accelerationKey: Key[Float] = FloatKey.make("acceleration")

      /** The deceleration applied at the end of motor motion for the axis in mm/sec2 */
      val decelerationKey: Key[Float] = FloatKey.make("deceleration")

      /**
       * The offset applied from the physical index switch/mark before setting the axis motor position to 0. Generally a useful
       * starting position (center of motion) for the mechanism
       */
      val indexOffsetKey: Key[Float] = FloatKey.make("indexOffset", Units.millimeter)

      /** The (generally slower) speed used when approaching the axis motor Index Switch for fine accuracy. (mm/sec) */
      val indexSpeedKey: Key[Float] = FloatKey.make("indexSpeed")

      /**
       * Used to determine successful completion of demanded moves for the axis. Determined by the needed positioning accuracy of
       * the mechanism
       */
      val inPositionThresholdKey: Key[Float] = FloatKey.make("inPositionThreshold", Units.millimeter)

    }

    /** Y axis config event, published only when configAxis or configLinearAxis cmd has completed during assembly startup */
    object YAxisConfigEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("yAxisConfig"))

      /** The maximum velocity for axis mechanism moves in mm/sec */
      val velocityKey: Key[Float] = FloatKey.make("velocity")

      /** The acceleration used to reach the configured velocity for the axis in mm/sec2 */
      val accelerationKey: Key[Float] = FloatKey.make("acceleration")

      /** The deceleration applied at the end of motor motion for the axis in mm/sec2 */
      val decelerationKey: Key[Float] = FloatKey.make("deceleration")

      /**
       * The offset applied from the physical index switch/mark before setting the axis motor position to 0. Generally a useful
       * starting position (center of motion) for the mechanism
       */
      val indexOffsetKey: Key[Float] = FloatKey.make("indexOffset", Units.millimeter)

      /** The (generally slower) speed used when approaching the axis motor Index Switch for fine accuracy. (mm/sec) */
      val indexSpeedKey: Key[Float] = FloatKey.make("indexSpeed")

      /**
       * Used to determine successful completion of demanded moves for the axis. Determined by the needed positioning accuracy of
       * the mechanism
       */
      val inPositionThresholdKey: Key[Float] = FloatKey.make("inPositionThreshold", Units.millimeter)

    }

    /** Z axis config event, published only when configAxis or configLinearAxis cmd has completed during assembly startup */
    object ZAxisConfigEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("zAxisConfig"))

      /** The maximum velocity for axis mechanism moves in mm/sec */
      val velocityKey: Key[Float] = FloatKey.make("velocity")

      /** The acceleration used to reach the configured velocity for the axis in mm/sec2 */
      val accelerationKey: Key[Float] = FloatKey.make("acceleration")

      /** The deceleration applied at the end of motor motion for the axis in mm/sec2 */
      val decelerationKey: Key[Float] = FloatKey.make("deceleration")

      /**
       * The offset applied from the physical index switch/mark before setting the axis motor position to 0. Generally a useful
       * starting position (center of motion) for the mechanism
       */
      val indexOffsetKey: Key[Float] = FloatKey.make("indexOffset", Units.millimeter)

      /** The (generally slower) speed used when approaching the axis motor Index Switch for fine accuracy. (mm/sec) */
      val indexSpeedKey: Key[Float] = FloatKey.make("indexSpeed")

      /**
       * Used to determine successful completion of demanded moves for the axis. Determined by the needed positioning accuracy of
       * the mechanism
       */
      val inPositionThresholdKey: Key[Float] = FloatKey.make("inPositionThreshold", Units.millimeter)

    }

    /** Event used to communicate that an unexpected condition occurred. */
    object ApsAlertEventEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("apsAlertEvent"))

      /** Unhandled errors require filling the message field, whereas other types should fill in the messageId */
      val messageSeverityKey: GChoiceKey = ChoiceKey.make("messageSeverity", "WARN", "ERROR", "UNHANDLED_ERROR")

      /**
       * Sensor originating warnings, errors, controller error codes/messages reported from the controller, and warnings/errors
       * that are a result of calculations
       */
      val sourceKey: GChoiceKey = ChoiceKey.make("source", "SENSOR", "HARDWARE_REPORTED", "CALCULATED")

      /**
       * Key used within the PEAS UI resource properties configuration file that holds all alert messages. Different from
       * procedure events, these alert messages contain placeholders for messageArgs in this alert event.
       */
      val messageIdKey: Key[String] = StringKey.make("messageId")

      /**
       * The message text obtained by the message Id key contains argument placeholders (e.g., {0}, {1}, etc.) that indicate where
       * variable argument values will be inserted. This field provides the ordered list of string values to substitute into the
       * message at the corresponding placeholder positions.
       */
      val messageArgsKey: Key[String] = StringKey.make("messageArgs")

      /** Message supplied by the event source for unhandled errors */
      val messageKey: Key[String] = StringKey.make("message")

    }

    /** Status of light derived from HCD I/O states */
    object InternalLightStatusEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("internalLightStatus"))

      /** status of light on/off state */
      val lightOnKey: GChoiceKey = ChoiceKey.make("lightOn", "ON", "OFF")

      /** light intensity read from galil (% of max) */
      val lightIntensityKey: Key[Float] = FloatKey.make("lightIntensity")

    }

    /** Assembly startup metrics */
    object StartupMetricsEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("startupMetrics"))

      /** Assembly initialization start time */
      val initStartTimeKey: Key[TAITime] = TAITimeKey.make("initStartTime")

      /** Assembly initialization completed time */
      val initCompletedTimeKey: Key[TAITime] = TAITimeKey.make("initCompletedTime")

      /** Assembly x-axis configuration start time */
      val xAxisConfigureStartTimeKey: Key[TAITime] = TAITimeKey.make("xAxisConfigureStartTime")

      /** Assembly x-axis configuration completed time */
      val xAxisConfigureCompletedTimeKey: Key[TAITime] = TAITimeKey.make("xAxisConfigureCompletedTime")

      /** Assembly y-axis configuration start time */
      val yAxisConfigureStartTimeKey: Key[TAITime] = TAITimeKey.make("yAxisConfigureStartTime")

      /** Assembly y-axis configuration completed time */
      val yAxisConfigureCompletedTimeKey: Key[TAITime] = TAITimeKey.make("yAxisConfigureCompletedTime")

      /** Assembly z-axis configuration start time */
      val zAxisConfigureStartTimeKey: Key[TAITime] = TAITimeKey.make("zAxisConfigureStartTime")

      /** Assembly z-axis configuration completed time */
      val zAxisConfigureCompletedTimeKey: Key[TAITime] = TAITimeKey.make("zAxisConfigureCompletedTime")

      /** Assembly x-axis homing started time */
      val xAxisHomeStartTimeKey: Key[TAITime] = TAITimeKey.make("xAxisHomeStartTime")

      /** Assembly x-axis homing completed time */
      val xAxisHomeCompletedTimeKey: Key[TAITime] = TAITimeKey.make("xAxisHomeCompletedTime")

      /** Assembly y-axis homing started time */
      val yAxisHomeStartTimeKey: Key[TAITime] = TAITimeKey.make("yAxisHomeStartTime")

      /** Assembly y-axis homing completed time */
      val yAxisHomeCompletedTimeKey: Key[TAITime] = TAITimeKey.make("yAxisHomeCompletedTime")

      /** Assembly z-axis homing started time */
      val zAxisHomeStartTimeKey: Key[TAITime] = TAITimeKey.make("zAxisHomeStartTime")

      /** Assembly z-axis homing completed time */
      val zAxisHomeCompletedTimeKey: Key[TAITime] = TAITimeKey.make("zAxisHomeCompletedTime")

    }

    /** X-axis motion metrics in response to commanding to a position */
    object XAxisMotionMetricsEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("xAxisMotionMetrics"))

      /** Motion cmd received time */
      val motionCmdReceivedKey: Key[TAITime] = TAITimeKey.make("motionCmdReceived")

      /** Motion cmd completed time */
      val motionCmdCompletedKey: Key[TAITime] = TAITimeKey.make("motionCmdCompleted")

      /** Axis position at the time of cmd receipt */
      val motionStartPositionKey: Key[Float] = FloatKey.make("motionStartPosition", Units.millimeter)

      /** Axis position at the time of cmd completion */
      val motionEndPositionKey: Key[Float] = FloatKey.make("motionEndPosition", Units.millimeter)

    }

    /** Y-axis motion metrics in response to commanding to a position */
    object YAxisMotionMetricsEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("yAxisMotionMetrics"))

      /** Motion cmd received time */
      val motionCmdReceivedKey: Key[TAITime] = TAITimeKey.make("motionCmdReceived")

      /** Motion cmd completed time */
      val motionCmdCompletedKey: Key[TAITime] = TAITimeKey.make("motionCmdCompleted")

      /** Axis position at the time of cmd receipt */
      val motionStartPositionKey: Key[Float] = FloatKey.make("motionStartPosition", Units.millimeter)

      /** Axis position at the time of cmd completion */
      val motionEndPositionKey: Key[Float] = FloatKey.make("motionEndPosition", Units.millimeter)

    }

    /** Z-axis motion metrics in response to commanding to a position */
    object ZAxisMotionMetricsEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("zAxisMotionMetrics"))

      /** Motion cmd received time */
      val motionCmdReceivedKey: Key[TAITime] = TAITimeKey.make("motionCmdReceived")

      /** Motion cmd completed time */
      val motionCmdCompletedKey: Key[TAITime] = TAITimeKey.make("motionCmdCompleted")

      /** Axis position at the time of cmd receipt */
      val motionStartPositionKey: Key[Float] = FloatKey.make("motionStartPosition", Units.millimeter)

      /** Axis position at the time of cmd completion */
      val motionEndPositionKey: Key[Float] = FloatKey.make("motionEndPosition", Units.millimeter)

    }

    /**
     * Configures the Galil controller channel for an assembly’s stage/motor. Calls HCD configLinearAxis specifying upper limit,
     * lower limit for linear axes, calls configRotationalAxis for rotational axes, and calls HCD configAxis for each axis,
     * specifying velocity, acceleration, deceleration, index offset, index speed, inPosition threshold.
     */
    object ConfigureCommand {
      val commandName: CommandName = CommandName("configure")

      /** The axis to configure */
      val axisKey: GChoiceKey = ChoiceKey.make("axis", "X AXIS", "Y AXIS", "Z AXIS")

    }

    /**
     * Positions each stage/motor controlled by the assembly to its home position, which is at the center of its range of motion,
     * and sets this as the zero position for the motor. All subsequent moves for a motor are relative to this position, sending a
     * subsequent position command to a motor with value zero (0) will return it to the home position
     */
    object HomeCommand {
      val commandName: CommandName = CommandName("home")

    }

    /**
     * Positions each stage/motor in the assembly to its default positions relative to the home zero position. The default
     * position is the nominal starting position for the assembly. All motion assemblies are moved to their default position when
     * commanding the APS system into “standby mode” during APS system initialization. The default position for each axis of the
     * assembly is part of the assembly configuration
     */
    object MoveToDefaultPositionCommand {
      val commandName: CommandName = CommandName("moveToDefaultPosition")

    }

    /**
     * Sends a stop command to the specified axis controlled by the assembly. This command is used for debugging using the APS
     * engineering user interface.
     */
    object StopCommand {
      val commandName: CommandName = CommandName("stop")

      /** The axis to configure */
      val axisKey: GChoiceKey = ChoiceKey.make("axis", "X AXIS", "Y AXIS", "Z AXIS")

    }

    /**
     * Positions stimulus source stage to the desired offset or absolute position. Used in INT and AIV alignment processes for
     * calibration and debugging
     */
    object PositionSourceCommand {
      val commandName: CommandName = CommandName("positionSource")

      /** relative offset or absolute positioning from home (0) position */
      val positioningMethodKey: GChoiceKey = ChoiceKey.make("positioningMethod", "ABSOLUTE", "RELATIVE")

      /** the absolute or relative X offset value to move the motor */
      val positionValueXKey: Key[Float] = FloatKey.make("positionValueX", Units.millimeter)

      /** the absolute or relative Y offset value to move the motor */
      val positionValueYKey: Key[Float] = FloatKey.make("positionValueY", Units.millimeter)

      /** the absolute or relative Z offset value to move the motor */
      val positionValueZKey: Key[Float] = FloatKey.make("positionValueZ", Units.millimeter)

    }

    /** Turns on and sets the intensity of the stimulus fiber light source. */
    object SetSourceIntensityCommand {
      val commandName: CommandName = CommandName("setSourceIntensity")

      /** Source power on or off */
      val sourcePowerKey: GChoiceKey = ChoiceKey.make("sourcePower", "ON", "OFF")

      /** The source intensity (% of max). */
      val sourceIntensityKey: Key[Float] = FloatKey.make("sourceIntensity")

    }

    /**
     * When a command error results in an automatic error recovery process, this command aborts that automatic process. Only valid
     * when assembly Command State is in the Error Recovery State.
     */
    object AbortErrorRecoveryCommand {
      val commandName: CommandName = CommandName("abortErrorRecovery")

    }

  }

}
