package aps.ics.assembly.icd

// This file contains the API for APS and was generated by the icd-db command.
// DO NOT EDIT.
// See https://github.com/tmtsoftware/icd for more information.

import csw.params.core.generics.KeyType._
import csw.params.commands.CommandName
import csw.params.events._
import csw.prefix.models._
import csw.params.core.generics._
import csw.params.core.models._
import csw.params.core.models.Coords._
import csw.time.core.models._

/**
 * Top level API for: APS
 */
//noinspection ScalaUnusedSymbol
object StimPupilMaskStageKeys {
  val subsystem = "APS"

  /** API for Assembly: APS.ICS.STIM.PupilMaskStage */
  object `ICS.STIM.PupilMaskStage` {
    val prefix: Prefix = Prefix(Subsystem.APS, "ICS.STIM.PupilMaskStage")

    /** PupilMaskStage status event */
    object StatusEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("status"))

      /** Current Assembly State */
      val assemblyStateKey: GChoiceKey = ChoiceKey.make("assemblyState", "PRE_HOMED", "OPERATIONAL", "DEGRADED", "FAULTED")

      /** Current HCD State of the HCD that the assembly communicates with */
      val hcdStateKey: GChoiceKey = ChoiceKey.make("hcdState", "UNINITIALIZED", "READY", "FAULTED")

      /** Status of last command */
      val commandStateKey: GChoiceKey = ChoiceKey.make("commandState", "IDLE", "PROCESSING", "ERROR_RECOVERY", "FAILED")

    }

    /** Status information for X axis */
    object XAxisStatusEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("xAxisStatus"))

      /** The current axis state */
      val axisStateKey: GChoiceKey = ChoiceKey.make("axisState", "LOST", "HOMING", "IDLE", "MOVING", "ERROR")

      /** The current axis position */
      val positionKey: Key[Float] = FloatKey.make("position", Units.millimeter)

      /** The current axis velocity mm/sec */
      val velocityKey: Key[Float] = FloatKey.make("velocity")

      /** True if the axis has been homed */
      val indexedKey: Key[Boolean] = BooleanKey.make("indexed")

      /** True if the axis has reached its target with sufficient accuracy. */
      val inPositionKey: Key[Boolean] = BooleanKey.make("inPosition")

    }

    /** Status information for Y axis */
    object YAxisStatusEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("yAxisStatus"))

      /** The current axis state */
      val axisStateKey: GChoiceKey = ChoiceKey.make("axisState", "LOST", "HOMING", "IDLE", "MOVING", "ERROR")

      /** The current axis position */
      val positionKey: Key[Float] = FloatKey.make("position", Units.millimeter)

      /** The current axis velocity mm/sec */
      val velocityKey: Key[Float] = FloatKey.make("velocity")

      /** True if the axis has been homed */
      val indexedKey: Key[Boolean] = BooleanKey.make("indexed")

      /** True if the axis has reached its target with sufficient accuracy. */
      val inPositionKey: Key[Boolean] = BooleanKey.make("inPosition")

    }

    /** Status information for Phi axis */
    object PhiAxisStatusEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("phiAxisStatus"))

      /** The current axis state */
      val axisStateKey: GChoiceKey = ChoiceKey.make("axisState", "LOST", "HOMING", "IDLE", "MOVING", "ERROR")

      /** The current axis position */
      val positionKey: Key[Float] = FloatKey.make("position", Units.degree)

      /** The current axis velocity deg/sec */
      val velocityKey: Key[Float] = FloatKey.make("velocity")

      /** True if the axis has been homed */
      val indexedKey: Key[Boolean] = BooleanKey.make("indexed")

      /** True if the axis has reached its target with sufficient accuracy. */
      val inPositionKey: Key[Boolean] = BooleanKey.make("inPosition")

    }

    /** X axis config event, published only when configAxis or configLinearAxis cmd has completed during assembly startup */
    object XAxisConfigEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("xAxisConfig"))

      /** The maximum velocity for axis mechanism moves in mm/sec */
      val velocityKey: Key[Float] = FloatKey.make("velocity")

      /** The acceleration used to reach the configured velocity for the axis in mm/sec2 */
      val accelerationKey: Key[Float] = FloatKey.make("acceleration")

      /** The deceleration applied at the end of motor motion for the axis in mm/sec2 */
      val decelerationKey: Key[Float] = FloatKey.make("deceleration")

      /**
       * The offset applied from the physical index switch/mark before setting the axis motor position to 0. Generally a useful
       * starting position (center of motion) for the mechanism
       */
      val indexOffsetKey: Key[Float] = FloatKey.make("indexOffset", Units.millimeter)

      /** The (generally slower) speed used when approaching the axis motor Index Switch for fine accuracy. (mm/sec) */
      val indexSpeedKey: Key[Float] = FloatKey.make("indexSpeed")

      /**
       * Used to determine successful completion of demanded moves for the axis. Determined by the needed positioning accuracy of
       * the mechanism
       */
      val inPositionThresholdKey: Key[Float] = FloatKey.make("inPositionThreshold", Units.millimeter)

    }

    /** Y axis config event, published only when configAxis or configLinearAxis cmd has completed during assembly startup */
    object YAxisConfigEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("yAxisConfig"))

      /** The maximum velocity for axis mechanism moves in mm/sec */
      val velocityKey: Key[Float] = FloatKey.make("velocity")

      /** The acceleration used to reach the configured velocity for the axis in mm/sec2 */
      val accelerationKey: Key[Float] = FloatKey.make("acceleration")

      /** The deceleration applied at the end of motor motion for the axis in mm/sec2 */
      val decelerationKey: Key[Float] = FloatKey.make("deceleration")

      /**
       * The offset applied from the physical index switch/mark before setting the axis motor position to 0. Generally a useful
       * starting position (center of motion) for the mechanism
       */
      val indexOffsetKey: Key[Float] = FloatKey.make("indexOffset", Units.millimeter)

      /** The (generally slower) speed used when approaching the axis motor Index Switch for fine accuracy. (mm/sec) */
      val indexSpeedKey: Key[Float] = FloatKey.make("indexSpeed")

      /**
       * Used to determine successful completion of demanded moves for the axis. Determined by the needed positioning accuracy of
       * the mechanism
       */
      val inPositionThresholdKey: Key[Float] = FloatKey.make("inPositionThreshold", Units.millimeter)

    }

    /** Phi axis config event, published only when configAxis or configRotatingAxis cmd has completed during assembly startup */
    object PhiAxisConfigEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("phiAxisConfig"))

      /** The maximum velocity for axis mechanism moves in deg/sec */
      val velocityKey: Key[Float] = FloatKey.make("velocity")

      /** The acceleration used to reach the configured velocity for the axis in deg/sec2 */
      val accelerationKey: Key[Float] = FloatKey.make("acceleration")

      /** The deceleration applied at the end of motor motion for the axis in deg/sec2 */
      val decelerationKey: Key[Float] = FloatKey.make("deceleration")

      /**
       * The offset applied from the physical index switch/mark before setting the axis motor position to 0. Generally a useful
       * starting position (center of motion) for the mechanism
       */
      val indexOffsetKey: Key[Float] = FloatKey.make("indexOffset", Units.degree)

      /** The (generally slower) speed used when approaching the axis motor Index Switch for fine accuracy. (deg/sec) */
      val indexSpeedKey: Key[Float] = FloatKey.make("indexSpeed")

      /**
       * Used to determine successful completion of demanded moves for the axis. Determined by the needed positioning accuracy of
       * the mechanism
       */
      val inPositionThresholdKey: Key[Float] = FloatKey.make("inPositionThreshold", Units.degree)

    }

    /** Event used to communicate a command failure to the user interface and/or Alignment Procedure Sequencer. */
    object ApsCommandFailureEventEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("apsCommandFailureEvent"))

      /** The user readable name of the source assembly or service that published the event */
      val sourceAssemblyKey: Key[String] = StringKey.make("sourceAssembly")

      /** Failure message supplied by the event source. */
      val messageKey: Key[String] = StringKey.make("message")

      /**
       * For failures and errors that have recovery modes (e.g. motion assemblies and detector assemblies) a state for the
       * progress of the recovery is given: started, completed, aborted. For failures that do not support auto recovery, the state
       * is NOT USED.
       */
      val recoveryStateKey: GChoiceKey = ChoiceKey.make("recoveryState", "STARTED", "COMPLETED", "ABORTED", "NOT_USED")

      /** The current auto-recovery retry number. */
      val recoveryRetryIndexKey: Key[Int] = IntKey.make("recoveryRetryIndex", Units.NoUnits)

      /** The total number of auto-recovery retries before recovery is abandoned. */
      val recoveryRetryCountKey: Key[Int] = IntKey.make("recoveryRetryCount", Units.NoUnits)

      /** Indicates if the current retry succeeded or failed. */
      val recoveryRetryStateKey: GChoiceKey = ChoiceKey.make("recoveryRetryState", "FAILURE", "SUCCESS")

    }

    /** Assembly startup metrics */
    object StartupMetricsEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("startupMetrics"))

      /** Assembly initialization start time */
      val initStartTimeKey: Key[TAITime] = TAITimeKey.make("initStartTime")

      /** Assembly initialization completed time */
      val initCompletedTimeKey: Key[TAITime] = TAITimeKey.make("initCompletedTime")

      /** Assembly x-axis configuration start time */
      val xAxisConfigureStartTimeKey: Key[TAITime] = TAITimeKey.make("xAxisConfigureStartTime")

      /** Assembly x-axis configuration completed time */
      val xAxisConfigureCompletedTimeKey: Key[TAITime] = TAITimeKey.make("xAxisConfigureCompletedTime")

      /** Assembly y-axis configuration start time */
      val yAxisConfigureStartTimeKey: Key[TAITime] = TAITimeKey.make("yAxisConfigureStartTime")

      /** Assembly y-axis configuration completed time */
      val yAxisConfigureCompletedTimeKey: Key[TAITime] = TAITimeKey.make("yAxisConfigureCompletedTime")

      /** Assembly phi-axis configuration start time */
      val phiAxisConfigureStartTimeKey: Key[TAITime] = TAITimeKey.make("phiAxisConfigureStartTime")

      /** Assembly phi-axis configuration completed time */
      val phiAxisConfigureCompletedTimeKey: Key[TAITime] = TAITimeKey.make("phiAxisConfigureCompletedTime")

      /** Assembly x-axis homing started time */
      val xAxisHomeStartTimeKey: Key[TAITime] = TAITimeKey.make("xAxisHomeStartTime")

      /** Assembly x-axis homing completed time */
      val xAxisHomeCompletedTimeKey: Key[TAITime] = TAITimeKey.make("xAxisHomeCompletedTime")

      /** Assembly y-axis homing started time */
      val yAxisHomeStartTimeKey: Key[TAITime] = TAITimeKey.make("yAxisHomeStartTime")

      /** Assembly y-axis homing completed time */
      val yAxisHomeCompletedTimeKey: Key[TAITime] = TAITimeKey.make("yAxisHomeCompletedTime")

      /** Assembly phi-axis homing started time */
      val phiAxisHomeStartTimeKey: Key[TAITime] = TAITimeKey.make("phiAxisHomeStartTime")

      /** Assembly phi-axis homing completed time */
      val phiAxisHomeCompletedTimeKey: Key[TAITime] = TAITimeKey.make("phiAxisHomeCompletedTime")

    }

    /** X-axis motion metrics in response to commanding to a position */
    object XAxisMotionMetricsEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("xAxisMotionMetrics"))

      /** Motion cmd received time */
      val motionCmdReceivedKey: Key[TAITime] = TAITimeKey.make("motionCmdReceived")

      /** Motion cmd completed time */
      val motionCmdCompletedKey: Key[TAITime] = TAITimeKey.make("motionCmdCompleted")

      /** Axis position at the time of cmd receipt */
      val motionStartPositionKey: Key[Float] = FloatKey.make("motionStartPosition", Units.millimeter)

      /** Axis position at the time of cmd completion */
      val motionEndPositionKey: Key[Float] = FloatKey.make("motionEndPosition", Units.millimeter)

    }

    /** Y-axis motion metrics in response to commanding to a position */
    object YAxisMotionMetricsEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("yAxisMotionMetrics"))

      /** Motion cmd received time */
      val motionCmdReceivedKey: Key[TAITime] = TAITimeKey.make("motionCmdReceived")

      /** Motion cmd completed time */
      val motionCmdCompletedKey: Key[TAITime] = TAITimeKey.make("motionCmdCompleted")

      /** Axis position at the time of cmd receipt */
      val motionStartPositionKey: Key[Float] = FloatKey.make("motionStartPosition", Units.millimeter)

      /** Axis position at the time of cmd completion */
      val motionEndPositionKey: Key[Float] = FloatKey.make("motionEndPosition", Units.millimeter)

    }

    /** Phi-axis motion metrics in response to commanding to a position */
    object PhiAxisMotionMetricsEvent {
      val eventKey: EventKey = EventKey(prefix, EventName("phiAxisMotionMetrics"))

      /** Motion cmd received time */
      val motionCmdReceivedKey: Key[TAITime] = TAITimeKey.make("motionCmdReceived")

      /** Motion cmd completed time */
      val motionCmdCompletedKey: Key[TAITime] = TAITimeKey.make("motionCmdCompleted")

      /** Axis position at the time of cmd receipt */
      val motionStartPositionKey: Key[Float] = FloatKey.make("motionStartPosition", Units.degree)

      /** Axis position at the time of cmd completion */
      val motionEndPositionKey: Key[Float] = FloatKey.make("motionEndPosition", Units.degree)

    }

    /**
     * Configures the Galil controller channel for an assembly’s stage/motor. Calls HCD configLinearAxis specifying upper limit,
     * lower limit for linear axes, calls configRotationalAxis for rotational axes, and calls HCD configAxis for each axis,
     * specifying velocity, acceleration, deceleration, index offset, index speed, inPosition threshold.
     */
    object ConfigureCommand {
      val commandName: CommandName = CommandName("configure")

      /** The stage to configure */
      val stageKey: GChoiceKey = ChoiceKey.make("stage", "X STAGE", "Y STAGE", "PHI STAGE")

    }

    /**
     * Positions each stage/motor controlled by the assembly to its home position, which is at the center of its range of motion,
     * and sets this as the zero position for the motor. All subsequent moves for a motor are relative to this position, sending a
     * subsequent position command to a motor with value zero (0) will return it to the home position
     */
    object HomeCommand {
      val commandName: CommandName = CommandName("home")

    }

    /**
     * Positions each stage/motor in the assembly to its default positions relative to the home zero position. The default
     * position is the nominal starting position for the assembly. All motion assemblies are moved to their default position when
     * commanding the APS system into “standby mode” during APS system initialization. The default position for each axis of the
     * assembly is part of the assembly configuration
     */
    object MoveToDefaultPositionCommand {
      val commandName: CommandName = CommandName("moveToDefaultPosition")

    }

    /**
     * Sends a stop command to the specified stage controlled by the assembly. This command is used for debugging using the APS
     * engineering user interface.
     */
    object StopCommand {
      val commandName: CommandName = CommandName("stop")

      /** The axis to configure */
      val stageKey: GChoiceKey = ChoiceKey.make("stage", "X STAGE", "Y STAGE", "PHI STAGE")

    }

    /**
     * Positions stimulus pupil mask stage the desired offset or absolute position. Used during INT and AIV to set alignment of
     * stimulus and also for diagnostic/debugging purposes
     */
    object PositionMaskStageCommand {
      val commandName: CommandName = CommandName("positionMaskStage")

      /** relative offset or absolute positioning from home (0) position */
      val positioningMethodKey: GChoiceKey = ChoiceKey.make("positioningMethod", "ABSOLUTE", "RELATIVE")

      /** the absolute or relative X offset value to move the motor */
      val positionValueXKey: Key[Float] = FloatKey.make("positionValueX", Units.millimeter)

      /** the absolute or relative Y offset value to move the motor */
      val positionValueYKey: Key[Float] = FloatKey.make("positionValueY", Units.millimeter)

      /** the absolute or relative Phi offset value to move the motor */
      val positionValuePhiKey: Key[Float] = FloatKey.make("positionValuePhi", Units.degree)

    }

    /**
     * When a command error results in an automatic error recovery process, this command aborts that automatic process. Only valid
     * when assembly Command State is in the Error Recovery State.
     */
    object AbortErrorRecoveryCommand {
      val commandName: CommandName = CommandName("abortErrorRecovery")

    }

  }

}
