# CSW container for the PIT Detector assembly (MOCK). No `connections` (no HCD).
name = "PitDetectorContainer"

components: [
  {
    prefix = "aps.ICS.PIT.Detector"
    componentType = assembly
    componentHandlerClassName = aps.ics.assembly.pit.PitDetectorHandlers
    locationServiceUsage = RegisterAndTrackServices
    connections = []
  }
]
