# CSW container for the PSH Detector assembly (MOCK). No `connections` (no HCD).
name = "PshDetectorContainer"

components: [
  {
    prefix = "aps.ICS.PSH.Detector"
    componentType = assembly
    componentHandlerClassName = aps.ics.assembly.psh.PshDetectorHandlers
    locationServiceUsage = RegisterAndTrackServices
    connections = []
  }
]
